import type { Lang } from "./treatments";

/*
 * Endgültige Kundentexte (Gesamtauftrag vom 3. Oktober 2026, abends): Bestätigungsmail, Mail nach dem Verschieben,
 * Erinnerungsmail, Kalenderdatei, Terminseite mit Verschieben. Deutsch wörtlich, die anderen Sprachen sinngemäß im
 * selben Ton, Betreffzeilen höchstens 40 Zeichen mit Datum und Uhrzeit vorn. Textliste: docs/TEXTE-MAILS.md.
 */
export const PHONE = "+49 151 58872566";
export const WA_LINK = "https://wa.me/4915158872566";
export const ADDRESS = "Hagenauer Straße 14, 10435 Berlin";
/** Google-Unternehmensprofil (Ersatz: https://maps.google.com/?cid=16946433859280785681) */
export const MAPS_LINK = "https://maps.app.goo.gl/c3KoXo6d9YU5P2wy8";
export const STUDIO = "PALO SKIN by Dr. Vogel";
export const BRAND = "PALO SKIN";
export const SIGNER = "Dr. med. Sebastian Vogel";

type When = (date: string, time: string) => string;

export interface MailTexts {
  /* Betreffzeilen */
  subjectBooked: When;
  subjectRequest: When;
  subjectRescheduled: When;
  subjectReminder: (time: string) => string;
  /* Absage durch die Kundin selbst (10. Oktober 2026): Betreff mit ausgeschriebenem Datum, ein Satz, Link zur Buchung */
  subjectCancelled: When;
  /** Datum mitten im Satz (dateIn), Uhrzeit wie in der Bestätigung */
  introCancelled: When;
  bookNewQ: string;
  bookNew: string;
  /* Bestätigungsmail */
  greeting: (firstName: string) => string;
  introBooked: string;
  introRequest: string;
  introRescheduled: string;
  mapL: string;
  punctual: string;
  both: string;
  saveQ: string;
  gcal: string;
  ical: string;
  ocal: string;
  oldCalendarNote: string;
  reminderNote: string;
  cancelInfo: string;
  manageLink: string;
  closing: string;
  /* Erinnerungsmail */
  introReminder: string;
  punctualShort: string;
  confirmQ: string;
  yes: string;
  notFit: string;
  rescheduleLink: string;
  closingReminder: string;
  /* Kalenderdatei */
  /** Kalendereintrag des Kunden (Datei, Google, Outlook): verlinkte Wörter zur Terminseite und der Hinweis auf die 24 Stunden */
  icsManage: string;
  icsWindow: string;
  /* Terminseite */
  pageTitle: string;
  pageIntro: string;
  windowOpen: string;
  windowShort: string;
  reschedule: string;
  cancel: string;
  cancelShort: string;
  cancelQ: string;
  cancelYes: string;
  cancelNo: string;
  orReschedule: string;
  doneYes: When;
  doneCancel: string;
  cancelledInfo: string;
  past: When;
  newBooking: string;
  invalid: string;
  waButton: string;
  testNote: string;
  /* Verschieben */
  rescheduleH: string;
  /** Verschieben-Seite im Design der Buchung (10. Oktober 2026): Überschrift in zwei Teilen, Kasten zum bisherigen Termin, Bestätigung */
  rsHA: string;
  rsHB: string;
  rsCurrentL: string;
  rsKeepP: string;
  rsDoneH: string;
  rescheduleP: When;
  rescheduleBtn: When;
  rescheduledH: When;
  rescheduledP: string;
  rescheduleGone: string;
  rescheduleLoading: string;
  rescheduleNone: string;
  rescheduleDown: string;
  /** Verfügbarkeit nicht prüfbar: der bisherige Termin bleibt */
  rescheduleUnavailable: string;
}

export const NB = " ";

export const MAIL_TEXTS: Record<Lang, MailTexts> = {
  de: {
    subjectBooked: (d, t) => `Gebucht: ${d}, ${t}`,
    subjectRequest: (d, t) => `Angefragt: ${d}, ${t}`,
    subjectRescheduled: (d, t) => `Verschoben: ${d}, ${t}`,
    subjectCancelled: (d, t) => `Abgesagt: ${d}, ${t}`,
    introCancelled: (d, t) => `Ihr Termin am ${d}, um ${t} ist abgesagt.`,
    bookNewQ: "Wenn Sie einen neuen Termin möchten, können Sie ihn hier buchen:",
    bookNew: "Neuen Termin buchen",
    subjectReminder: (t) => `Bitte kurz bestätigen: morgen, ${t}`,
    greeting: (n) => `Hallo ${n},`,
    introBooked: "schön, dass Sie zu uns kommen! Wir freuen uns auf Sie:",
    introRequest: "schön, dass Sie zu uns kommen möchten! Wir haben die Zeit für Sie vorgemerkt und melden uns kurz per WhatsApp:",
    introRescheduled: "Ihr Termin ist verschoben. Wir freuen uns auf Sie:",
    mapL: "So finden Sie uns",
    punctual: `Ihre Zeit ist uns wichtig: Bei ${BRAND} beginnt Ihr Termin pünktlich, in der Regel ganz ohne Wartezeit. Kommen Sie bitte zur vereinbarten Zeit oder höchstens fünf Minuten vorher. Falls Sie später kommen, bleibt entsprechend weniger Zeit für Ihren Termin, damit auch die nächsten Kunden pünktlich starten.`,
    both: "Für Sie beide haben wir Zeit eingeplant.",
    saveQ: "Möchten Sie den Termin gleich im Kalender speichern?",
    gcal: "Google Kalender",
    ical: "iPhone-Kalender",
    ocal: "Outlook",
    oldCalendarNote: "Falls Sie den alten Termin in Ihrem Kalender gespeichert haben, löschen Sie ihn bitte dort.",
    reminderNote: "Am Tag vorher erinnern wir Sie noch einmal.",
    cancelInfo: "Den Termin verschieben oder absagen können Sie bis 24 Stunden vorher über diesen Link.",
    manageLink: "Termin verschieben oder absagen",
    closing: "Bis bald!",
    introReminder: `morgen sehen wir uns bei ${BRAND}, wir freuen uns auf Sie!`,
    punctualShort: "Ihr Termin beginnt pünktlich, in der Regel ganz ohne Wartezeit. Kommen Sie bitte zur vereinbarten Zeit oder höchstens fünf Minuten vorher.",
    confirmQ: "Passt der Termin weiterhin für Sie? Dann bestätigen Sie bitte kurz mit einem Klick:",
    yes: "Ja, ich komme",
    notFit: "Passt es doch nicht? Dann verschieben Sie den Termin hier:",
    rescheduleLink: "Termin verschieben",
    closingReminder: "Bis morgen!",
    icsManage: "Termin ansehen, verschieben oder absagen",
    icsWindow: "(bis 24 Stunden vorher)",
    pageTitle: "Ihr Termin",
    pageIntro: `hier finden Sie Ihren Termin bei ${BRAND}:`,
    windowOpen: "Den Termin verschieben oder absagen können Sie bis 24 Stunden vorher.",
    windowShort: "Sie können nicht kommen? Bitte sagen Sie uns kurz Bescheid, dann können wir die Zeit noch vergeben.",
    reschedule: "Termin verschieben",
    cancel: "Termin absagen",
    cancelShort: "Leider verhindert",
    cancelQ: "Möchten Sie Ihren Termin absagen?",
    cancelYes: "Termin absagen",
    cancelNo: "Termin behalten",
    orReschedule: "Oder lieber verschieben?",
    doneYes: (d, t) => `Danke! Wir freuen uns auf Sie am ${d}, um ${t}.`,
    doneCancel: "Ihr Termin ist abgesagt. Wir freuen uns, Sie ein anderes Mal zu sehen.",
    cancelledInfo: "Ihr Termin ist bereits abgesagt. Möchten Sie einen neuen Termin finden?",
    past: (d, t) => `Der Termin war am ${d}, um ${t}. Möchten Sie einen neuen Termin vereinbaren?`,
    newBooking: "Neuen Termin buchen",
    invalid: "Dieser Link lässt sich nicht öffnen. Schreiben Sie uns kurz per WhatsApp, wir helfen Ihnen gern weiter.",
    waButton: "Per WhatsApp schreiben",
    testNote: "Testbetrieb: Diese Nachricht gehört zu einer Testbuchung.",
    rescheduleH: "Neue Zeit wählen",
    rsHA: "Wann passt es", rsHB: "Ihnen besser?", rsCurrentL: "Ihr bisheriger Termin",
    rsKeepP: "Er bleibt für Sie reserviert, bis Sie eine neue Zeit gewählt haben.",
    rsDoneH: "Ihr Termin ist verschoben.",
    rescheduleP: (d, t) => `Ihr bisheriger Termin: ${d}, ${t}. Er bleibt für Sie reserviert, bis Sie eine neue Zeit gewählt haben.`,
    rescheduleBtn: (d, t) => `Auf ${d}, ${t} verschieben`,
    rescheduledH: (d, t) => `Verschoben! Ihr neuer Termin: ${d}, ${t}.`,
    rescheduledP: "Die neue Bestätigung kommt gleich per E-Mail.",
    rescheduleGone: "Diese Zeit ist leider gerade vergeben worden. Bitte wählen Sie eine andere.",
    rescheduleLoading: "Freie Zeiten werden geladen …",
    rescheduleNone: "Online ist gerade keine passende Zeit frei. Schreiben Sie uns gern per WhatsApp.",
    rescheduleDown: "Gerade hakt es bei uns. Bitte versuchen Sie es gleich noch einmal oder schreiben Sie uns per WhatsApp.",
    rescheduleUnavailable: "Wir können die freien Zeiten gerade nicht prüfen. Ihr bisheriger Termin bleibt unverändert. Bitte versuchen Sie es in ein paar Minuten noch einmal. Oder schreiben Sie uns kurz per WhatsApp.",
  },
  en: {
    subjectBooked: (d, t) => `Booked: ${d}, ${t}`,
    subjectRequest: (d, t) => `Requested: ${d}, ${t}`,
    subjectRescheduled: (d, t) => `Rescheduled: ${d}, ${t}`,
    subjectCancelled: (d, t) => `Cancelled: ${d}, ${t}`,
    introCancelled: (d, t) => `Your appointment on ${d} at ${t} has been cancelled.`,
    bookNewQ: "If you would like a new appointment, you can book it here:",
    bookNew: "Book a new appointment",
    subjectReminder: (t) => `Please confirm: tomorrow, ${t}`,
    greeting: (n) => `Hello ${n},`,
    introBooked: "lovely that you’re coming to see us! We look forward to seeing you:",
    introRequest: "lovely that you’d like to come! We have reserved the time for you and will be in touch shortly on WhatsApp:",
    introRescheduled: "Your appointment has been rescheduled. We look forward to seeing you:",
    mapL: "How to find us",
    punctual: `Your time matters to us: at ${BRAND}, your appointment starts on time, usually with no waiting at all. Please arrive at the agreed time or at most five minutes early. If you arrive later, there is correspondingly less time for your appointment, so the next clients can also start on time.`,
    both: "We have planned time for both of you.",
    saveQ: "Would you like to save the appointment to your calendar right away?",
    gcal: "Google Calendar",
    ical: "iPhone Calendar",
    ocal: "Outlook",
    oldCalendarNote: "If you saved the previous appointment in your calendar, please delete it there.",
    reminderNote: "We’ll remind you once more the day before.",
    cancelInfo: "You can reschedule or cancel the appointment up to 24 hours in advance via this link.",
    manageLink: "Reschedule or cancel appointment",
    closing: "See you soon!",
    introReminder: `we’ll see you tomorrow at ${BRAND}, we look forward to seeing you!`,
    punctualShort: "Your appointment starts on time, usually with no waiting at all. Please arrive at the agreed time or at most five minutes early.",
    confirmQ: "Does the appointment still suit you? Then please confirm briefly with one click:",
    yes: "Yes, I’ll be there",
    notFit: "Doesn’t suit you after all? Then reschedule the appointment here:",
    rescheduleLink: "Reschedule appointment",
    closingReminder: "See you tomorrow!",
    icsManage: "View, reschedule or cancel your appointment",
    icsWindow: "(up to 24 hours in advance)",
    pageTitle: "Your appointment",
    pageIntro: `here is your appointment at ${BRAND}:`,
    windowOpen: "You can reschedule or cancel the appointment up to 24 hours in advance.",
    windowShort: "Can’t make it? Please let us know briefly so we can still give the time to someone else.",
    reschedule: "Reschedule appointment",
    cancel: "Cancel appointment",
    cancelShort: "Unable to come",
    cancelQ: "Would you like to cancel your appointment?",
    cancelYes: "Cancel appointment",
    cancelNo: "Keep appointment",
    orReschedule: "Or would you rather reschedule?",
    doneYes: (d, t) => `Thank you! We look forward to seeing you on ${d} at ${t}.`,
    doneCancel: "Your appointment is cancelled. We look forward to seeing you another time.",
    cancelledInfo: "Your appointment has already been cancelled. Would you like to find a new one?",
    past: (d, t) => `The appointment was on ${d} at ${t}. Would you like to arrange a new one?`,
    newBooking: "Book a new appointment",
    invalid: "This link cannot be opened. Send us a quick WhatsApp message and we’ll be happy to help.",
    waButton: "Message us on WhatsApp",
    testNote: "Test mode: this message belongs to a test booking.",
    rescheduleH: "Choose a new time",
    rsHA: "When would", rsHB: "suit you better?", rsCurrentL: "Your current appointment",
    rsKeepP: "It stays reserved for you until you have chosen a new time.",
    rsDoneH: "Your appointment has been moved.",
    rescheduleP: (d, t) => `Your current appointment: ${d}, ${t}. It stays reserved for you until you have chosen a new time.`,
    rescheduleBtn: (d, t) => `Move to ${d}, ${t}`,
    rescheduledH: (d, t) => `Rescheduled! Your new appointment: ${d}, ${t}.`,
    rescheduledP: "The new confirmation will reach you by email in a moment.",
    rescheduleGone: "Unfortunately this time has just been taken. Please choose another.",
    rescheduleLoading: "Loading available times …",
    rescheduleNone: "There is no suitable time available online right now. Feel free to message us on WhatsApp.",
    rescheduleDown: "Something’s not working on our side right now. Please try again in a moment or message us on WhatsApp.",
    rescheduleUnavailable: "We can’t check availability right now. Your current appointment stays as it is. Please try again in a few minutes. Or send us a quick message on WhatsApp.",
  },
  es: {
    subjectBooked: (d, t) => `Reservado: ${d}, ${t}`,
    subjectRequest: (d, t) => `Solicitado: ${d}, ${t}`,
    subjectRescheduled: (d, t) => `Cambiado: ${d}, ${t}`,
    subjectCancelled: (d, t) => `Cancelada: ${d}, ${t}`,
    introCancelled: (d, t) => `Su cita del ${d} a las ${t} ha sido cancelada.`,
    bookNewQ: "Si desea una nueva cita, puede reservarla aquí:",
    bookNew: "Reservar una nueva cita",
    subjectReminder: (t) => `Por favor, confirme: mañana, ${t}`,
    greeting: (n) => `Hola ${n},`,
    introBooked: "¡qué bien que venga a vernos! Le esperamos:",
    introRequest: "¡qué bien que quiera venir! Hemos reservado la hora para usted y le escribimos en breve por WhatsApp:",
    introRescheduled: "Su cita ha sido cambiada. Le esperamos:",
    mapL: "Cómo llegar",
    punctual: `Su tiempo es importante para nosotros: en ${BRAND} su cita empieza puntual, por lo general sin ninguna espera. Venga, por favor, a la hora acordada o como máximo cinco minutos antes. Si llega más tarde, quedará menos tiempo para su cita, para que los siguientes clientes también empiecen puntuales.`,
    both: "Hemos reservado tiempo para los dos.",
    saveQ: "¿Quiere guardar la cita en su calendario ahora mismo?",
    gcal: "Google Calendar",
    ical: "Calendario del iPhone",
    ocal: "Outlook",
    oldCalendarNote: "Si guardó la cita anterior en su calendario, elimínela allí, por favor.",
    reminderNote: "El día anterior se lo recordamos una vez más.",
    cancelInfo: "Puede cambiar o cancelar la cita hasta 24 horas antes a través de este enlace.",
    manageLink: "Cambiar o cancelar la cita",
    closing: "¡Hasta pronto!",
    introReminder: `mañana nos vemos en ${BRAND}, ¡le esperamos!`,
    punctualShort: "Su cita empieza puntual, por lo general sin ninguna espera. Venga, por favor, a la hora acordada o como máximo cinco minutos antes.",
    confirmQ: "¿La cita le sigue viniendo bien? Entonces confírmela brevemente con un clic:",
    yes: "Sí, voy a ir",
    notFit: "¿Al final no le viene bien? Cambie la cita aquí:",
    rescheduleLink: "Cambiar la cita",
    closingReminder: "¡Hasta mañana!",
    icsManage: "Ver, cambiar o cancelar su cita",
    icsWindow: "(hasta 24 horas antes)",
    pageTitle: "Su cita",
    pageIntro: `aquí tiene su cita en ${BRAND}:`,
    windowOpen: "Puede cambiar o cancelar la cita hasta 24 horas antes.",
    windowShort: "¿No puede venir? Avísenos brevemente, así aún podemos dar la hora a otra persona.",
    reschedule: "Cambiar la cita",
    cancel: "Cancelar la cita",
    cancelShort: "No puedo ir",
    cancelQ: "¿Quiere cancelar su cita?",
    cancelYes: "Cancelar la cita",
    cancelNo: "Mantener la cita",
    orReschedule: "¿O prefiere cambiarla?",
    doneYes: (d, t) => `¡Gracias! Le esperamos el ${d} a las ${t}.`,
    doneCancel: "Su cita queda cancelada. Nos alegrará verle en otra ocasión.",
    cancelledInfo: "Su cita ya está cancelada. ¿Quiere buscar una nueva?",
    past: (d, t) => `La cita fue el ${d} a las ${t}. ¿Quiere concertar una nueva?`,
    newBooking: "Reservar una nueva cita",
    invalid: "Este enlace no se puede abrir. Escríbanos un momento por WhatsApp, le ayudamos con gusto.",
    waButton: "Escribir por WhatsApp",
    testNote: "Modo de prueba: este mensaje pertenece a una reserva de prueba.",
    rescheduleH: "Elegir una nueva hora",
    rsHA: "¿Cuándo le viene", rsHB: "mejor?", rsCurrentL: "Su cita actual",
    rsKeepP: "Se la mantenemos reservada hasta que elija una nueva hora.",
    rsDoneH: "Su cita ha sido cambiada.",
    rescheduleP: (d, t) => `Su cita actual: ${d}, ${t}. Queda reservada para usted hasta que elija una nueva hora.`,
    rescheduleBtn: (d, t) => `Cambiar al ${d}, ${t}`,
    rescheduledH: (d, t) => `¡Cambiada! Su nueva cita: ${d}, ${t}.`,
    rescheduledP: "La nueva confirmación le llega enseguida por correo electrónico.",
    rescheduleGone: "Lamentablemente esta hora acaba de ocuparse. Elija otra, por favor.",
    rescheduleLoading: "Cargando horas disponibles …",
    rescheduleNone: "Ahora mismo no hay ninguna hora libre en línea. Escríbanos con gusto por WhatsApp.",
    rescheduleDown: "Ahora mismo algo falla por nuestra parte. Inténtelo de nuevo en un momento o escríbanos por WhatsApp.",
    rescheduleUnavailable: "En este momento no podemos comprobar la disponibilidad. Su cita actual se mantiene igual. Inténtelo de nuevo en unos minutos. O escríbanos brevemente por WhatsApp.",
  },
  fr: {
    subjectBooked: (d, t) => `Réservé${NB}: ${d}, ${t}`,
    subjectRequest: (d, t) => `Demandé${NB}: ${d}, ${t}`,
    subjectRescheduled: (d, t) => `Déplacé${NB}: ${d}, ${t}`,
    subjectCancelled: (d, t) => `Annulé${NB}: ${d}, ${t}`,
    introCancelled: (d, t) => `Votre rendez-vous du ${d} à ${t} est annulé.`,
    bookNewQ: `Si vous souhaitez un nouveau rendez-vous, vous pouvez le réserver ici${NB}:`,
    bookNew: "Réserver un nouveau rendez-vous",
    subjectReminder: (t) => `Merci de confirmer${NB}: demain, ${t}`,
    greeting: (n) => `Bonjour ${n},`,
    introBooked: `quel plaisir de vous accueillir${NB}! Nous avons hâte de vous voir${NB}:`,
    introRequest: `quel plaisir que vous souhaitiez venir${NB}! Nous avons réservé le créneau pour vous et vous écrivons rapidement sur WhatsApp${NB}:`,
    introRescheduled: `Votre rendez-vous a été déplacé. Nous avons hâte de vous voir${NB}:`,
    mapL: "Comment nous trouver",
    punctual: `Votre temps nous est précieux${NB}: chez ${BRAND}, votre rendez-vous commence à l’heure, en général sans aucune attente. Merci de venir à l’heure convenue ou au plus cinq minutes avant. Si vous arrivez plus tard, il restera d’autant moins de temps pour votre rendez-vous, afin que les clients suivants commencent eux aussi à l’heure.`,
    both: "Nous avons prévu du temps pour vous deux.",
    saveQ: `Souhaitez-vous enregistrer le rendez-vous tout de suite dans votre agenda${NB}?`,
    gcal: "Google Agenda",
    ical: "Calendrier iPhone",
    ocal: "Outlook",
    oldCalendarNote: "Si vous aviez enregistré l’ancien rendez-vous dans votre agenda, merci de l’y supprimer.",
    reminderNote: "La veille, nous vous enverrons un rappel.",
    cancelInfo: "Vous pouvez déplacer ou annuler le rendez-vous jusqu’à 24 heures avant via ce lien.",
    manageLink: "Déplacer ou annuler le rendez-vous",
    closing: `À bientôt${NB}!`,
    introReminder: `nous nous voyons demain chez ${BRAND}, nous avons hâte de vous accueillir${NB}!`,
    punctualShort: "Votre rendez-vous commence à l’heure, en général sans aucune attente. Merci de venir à l’heure convenue ou au plus cinq minutes avant.",
    confirmQ: `Le rendez-vous vous convient toujours${NB}? Alors confirmez-le en un clic${NB}:`,
    yes: "Oui, je viens",
    notFit: `Cela ne convient finalement pas${NB}? Déplacez le rendez-vous ici${NB}:`,
    rescheduleLink: "Déplacer le rendez-vous",
    closingReminder: `À demain${NB}!`,
    icsManage: "Voir, déplacer ou annuler votre rendez-vous",
    icsWindow: "(jusqu’à 24 heures avant)",
    pageTitle: "Votre rendez-vous",
    pageIntro: `voici votre rendez-vous chez ${BRAND}${NB}:`,
    windowOpen: "Vous pouvez déplacer ou annuler le rendez-vous jusqu’à 24 heures avant.",
    windowShort: `Vous ne pouvez pas venir${NB}? Dites-le-nous en un mot, nous pourrons encore proposer le créneau à quelqu’un d’autre.`,
    reschedule: "Déplacer le rendez-vous",
    cancel: "Annuler le rendez-vous",
    cancelShort: "Empêchement",
    cancelQ: `Souhaitez-vous annuler votre rendez-vous${NB}?`,
    cancelYes: "Annuler le rendez-vous",
    cancelNo: "Garder le rendez-vous",
    orReschedule: `Ou plutôt le déplacer${NB}?`,
    doneYes: (d, t) => `Merci${NB}! Nous avons hâte de vous accueillir le ${d} à ${t}.`,
    doneCancel: "Votre rendez-vous est annulé. Au plaisir de vous voir une autre fois.",
    cancelledInfo: `Votre rendez-vous est déjà annulé. Souhaitez-vous en trouver un nouveau${NB}?`,
    past: (d, t) => `Le rendez-vous était le ${d} à ${t}. Souhaitez-vous en convenir un nouveau${NB}?`,
    newBooking: "Réserver un nouveau rendez-vous",
    invalid: "Ce lien ne peut pas être ouvert. Écrivez-nous un petit mot sur WhatsApp, nous vous aiderons volontiers.",
    waButton: "Écrire sur WhatsApp",
    testNote: `Mode test${NB}: ce message concerne une réservation de test.`,
    rescheduleH: "Choisir un nouveau créneau",
    rsHA: "Quel moment vous", rsHB: "conviendrait mieux ?", rsCurrentL: "Votre rendez-vous actuel",
    rsKeepP: "Il reste réservé pour vous jusqu’à ce que vous ayez choisi un nouvel horaire.",
    rsDoneH: "Votre rendez-vous est déplacé.",
    rescheduleP: (d, t) => `Votre rendez-vous actuel${NB}: ${d}, ${t}. Il reste réservé pour vous jusqu’à ce que vous ayez choisi un nouveau créneau.`,
    rescheduleBtn: (d, t) => `Déplacer au ${d}, ${t}`,
    rescheduledH: (d, t) => `Déplacé${NB}! Votre nouveau rendez-vous${NB}: ${d}, ${t}.`,
    rescheduledP: "La nouvelle confirmation arrive dans un instant par e-mail.",
    rescheduleGone: "Ce créneau vient malheureusement d’être pris. Merci d’en choisir un autre.",
    rescheduleLoading: "Chargement des créneaux disponibles …",
    rescheduleNone: "Aucun créneau n’est disponible en ligne pour le moment. Écrivez-nous volontiers sur WhatsApp.",
    rescheduleDown: "Quelque chose ne fonctionne pas de notre côté pour le moment. Réessayez dans un instant ou écrivez-nous sur WhatsApp.",
    rescheduleUnavailable: "Nous ne pouvons pas vérifier les disponibilités pour le moment. Votre rendez-vous actuel reste inchangé. Merci de réessayer dans quelques minutes. Ou écrivez-nous un petit mot sur WhatsApp.",
  },
  pt: {
    subjectBooked: (d, t) => `Marcado: ${d}, ${t}`,
    subjectRequest: (d, t) => `Pedido: ${d}, ${t}`,
    subjectRescheduled: (d, t) => `Remarcado: ${d}, ${t}`,
    subjectCancelled: (d, t) => `Cancelada: ${d}, ${t}`,
    introCancelled: (d, t) => `Sua consulta de ${d}, às ${t}, foi cancelada.`,
    bookNewQ: "Se quiser uma nova consulta, você pode agendá-la aqui:",
    bookNew: "Agendar nova consulta",
    subjectReminder: (t) => `Confirme, por favor: amanhã, ${t}`,
    greeting: (n) => `Olá ${n},`,
    introBooked: "que bom que você vem nos ver! Esperamos por você:",
    introRequest: "que bom que você quer vir! Reservamos o horário para você e falamos em breve pelo WhatsApp:",
    introRescheduled: "Sua consulta foi remarcada. Esperamos por você:",
    mapL: "Como chegar",
    punctual: `Seu tempo é importante para nós: na ${BRAND}, sua consulta começa pontualmente, em geral sem nenhuma espera. Por favor, chegue na hora combinada ou no máximo cinco minutos antes. Se chegar mais tarde, sobra menos tempo para a sua consulta, para que os próximos clientes também comecem no horário.`,
    both: "Reservamos tempo para vocês dois.",
    saveQ: "Quer salvar a consulta no seu calendário agora mesmo?",
    gcal: "Google Agenda",
    ical: "Calendário do iPhone",
    ocal: "Outlook",
    oldCalendarNote: "Se você salvou a consulta anterior no seu calendário, apague-a lá, por favor.",
    reminderNote: "No dia anterior, lembramos você mais uma vez.",
    cancelInfo: "Você pode remarcar ou cancelar a consulta até 24 horas antes por este link.",
    manageLink: "Remarcar ou cancelar a consulta",
    closing: "Até breve!",
    introReminder: `amanhã nos vemos na ${BRAND}, esperamos por você!`,
    punctualShort: "Sua consulta começa pontualmente, em geral sem nenhuma espera. Por favor, chegue na hora combinada ou no máximo cinco minutos antes.",
    confirmQ: "A consulta continua boa para você? Então confirme rapidamente com um clique:",
    yes: "Sim, eu vou",
    notFit: "No fim não dá certo? Então remarque a consulta aqui:",
    rescheduleLink: "Remarcar a consulta",
    closingReminder: "Até amanhã!",
    icsManage: "Ver, remarcar ou cancelar sua consulta",
    icsWindow: "(até 24 horas antes)",
    pageTitle: "Sua consulta",
    pageIntro: `aqui está a sua consulta na ${BRAND}:`,
    windowOpen: "Você pode remarcar ou cancelar a consulta até 24 horas antes.",
    windowShort: "Não vai conseguir vir? Avise rapidamente, assim ainda podemos oferecer o horário a outra pessoa.",
    reschedule: "Remarcar a consulta",
    cancel: "Cancelar a consulta",
    cancelShort: "Não consigo ir",
    cancelQ: "Quer cancelar a sua consulta?",
    cancelYes: "Cancelar a consulta",
    cancelNo: "Manter a consulta",
    orReschedule: "Ou prefere remarcar?",
    doneYes: (d, t) => `Obrigado! Esperamos por você em ${d}, às ${t}.`,
    doneCancel: "Sua consulta foi cancelada. Será um prazer ver você em outra ocasião.",
    cancelledInfo: "Sua consulta já foi cancelada. Quer encontrar um novo horário?",
    past: (d, t) => `A consulta foi em ${d}, às ${t}. Quer marcar uma nova?`,
    newBooking: "Marcar uma nova consulta",
    invalid: "Este link não pode ser aberto. Mande uma mensagem rápida pelo WhatsApp, ajudamos com prazer.",
    waButton: "Escrever pelo WhatsApp",
    testNote: "Modo de teste: esta mensagem pertence a uma reserva de teste.",
    rescheduleH: "Escolher um novo horário",
    rsHA: "Quando fica", rsHB: "melhor para você?", rsCurrentL: "Seu horário atual",
    rsKeepP: "Ele continua reservado para você até que escolha um novo horário.",
    rsDoneH: "Seu horário foi remarcado.",
    rescheduleP: (d, t) => `Sua consulta atual: ${d}, ${t}. Ela continua reservada para você até você escolher um novo horário.`,
    rescheduleBtn: (d, t) => `Remarcar para ${d}, ${t}`,
    rescheduledH: (d, t) => `Remarcado! Sua nova consulta: ${d}, ${t}.`,
    rescheduledP: "A nova confirmação chega já por e-mail.",
    rescheduleGone: "Infelizmente este horário acabou de ser ocupado. Escolha outro, por favor.",
    rescheduleLoading: "Carregando horários livres …",
    rescheduleNone: "No momento não há nenhum horário livre online. Fale conosco pelo WhatsApp.",
    rescheduleDown: "Algo não está funcionando do nosso lado agora. Tente de novo em instantes ou fale conosco pelo WhatsApp.",
    rescheduleUnavailable: "No momento não conseguimos verificar a disponibilidade. Sua consulta atual continua igual. Tente de novo em alguns minutos. Ou mande uma mensagem rápida pelo WhatsApp.",
  },
  it: {
    subjectBooked: (d, t) => `Prenotato: ${d}, ${t}`,
    subjectRequest: (d, t) => `Richiesto: ${d}, ${t}`,
    subjectRescheduled: (d, t) => `Spostato: ${d}, ${t}`,
    subjectCancelled: (d, t) => `Annullato: ${d}, ${t}`,
    introCancelled: (d, t) => `Il Suo appuntamento di ${d} alle ${t} è stato annullato.`,
    bookNewQ: "Se desidera un nuovo appuntamento, può prenotarlo qui:",
    bookNew: "Prenoti un nuovo appuntamento",
    subjectReminder: (t) => `Confermi, per favore: domani, ${t}`,
    greeting: (n) => `Buongiorno ${n},`,
    introBooked: "che bello che venga da noi! La aspettiamo con piacere:",
    introRequest: "che bello che desideri venire da noi! Abbiamo riservato l’orario per Lei e Le scriveremo a breve su WhatsApp:",
    introRescheduled: "il Suo appuntamento è stato spostato. La aspettiamo con piacere:",
    mapL: "Come raggiungerci",
    punctual: `Il Suo tempo è importante per noi: da ${BRAND} il Suo appuntamento inizia puntuale, di norma senza alcuna attesa. La preghiamo di arrivare all’orario concordato o al massimo cinque minuti prima. Se arriva più tardi, resterà proporzionalmente meno tempo per il Suo appuntamento, così che anche i clienti successivi possano iniziare puntuali.`,
    both: "Abbiamo previsto il tempo per entrambe le persone.",
    saveQ: "Desidera salvare subito l’appuntamento nel calendario?",
    gcal: "Google Calendar",
    ical: "Calendario iPhone",
    ocal: "Outlook",
    oldCalendarNote: "Se aveva salvato il vecchio appuntamento nel Suo calendario, La preghiamo di eliminarlo.",
    reminderNote: "Il giorno prima Le invieremo un promemoria.",
    cancelInfo: "Può spostare o disdire l’appuntamento fino a 24 ore prima tramite questo link.",
    manageLink: "Sposta o disdici l’appuntamento",
    closing: "A presto!",
    introReminder: `domani ci vediamo da ${BRAND}, La aspettiamo con piacere!`,
    punctualShort: "Il Suo appuntamento inizia puntuale, di norma senza alcuna attesa. La preghiamo di arrivare all’orario concordato o al massimo cinque minuti prima.",
    confirmQ: "L’appuntamento Le va ancora bene? Allora lo confermi brevemente con un clic:",
    yes: "Sì, ci sarò",
    notFit: "Alla fine non Le va bene? Allora sposti l’appuntamento qui:",
    rescheduleLink: "Sposta l’appuntamento",
    closingReminder: "A domani!",
    icsManage: "Vedi, sposta o disdici l’appuntamento",
    icsWindow: "(fino a 24 ore prima)",
    pageTitle: "Il Suo appuntamento",
    pageIntro: `ecco il Suo appuntamento da ${BRAND}:`,
    windowOpen: "Può spostare o disdire l’appuntamento fino a 24 ore prima.",
    windowShort: "Non può venire? Ce lo faccia sapere brevemente, così possiamo ancora assegnare l’orario a qualcun altro.",
    reschedule: "Sposta l’appuntamento",
    cancel: "Disdici l’appuntamento",
    cancelShort: "Purtroppo non posso",
    cancelQ: "Desidera disdire il Suo appuntamento?",
    cancelYes: "Disdici l’appuntamento",
    cancelNo: "Mantieni l’appuntamento",
    orReschedule: "Oppure preferisce spostarlo?",
    doneYes: (d, t) => `Grazie! La aspettiamo ${d} alle ${t}.`,
    doneCancel: "Il Suo appuntamento è stato disdetto. Saremo lieti di vederLa un’altra volta.",
    cancelledInfo: "Il Suo appuntamento è già stato disdetto. Desidera trovare un nuovo appuntamento?",
    past: (d, t) => `L’appuntamento era ${d} alle ${t}. Desidera fissarne uno nuovo?`,
    newBooking: "Prenota un nuovo appuntamento",
    invalid: "Questo link non si può aprire. Ci scriva due righe su WhatsApp, La aiutiamo volentieri.",
    waButton: "Scrivere su WhatsApp",
    testNote: "Modalità di prova: questo messaggio riguarda una prenotazione di prova.",
    rescheduleH: "Scelga un nuovo orario",
    rsHA: "Quando Le", rsHB: "va meglio?", rsCurrentL: "Il Suo appuntamento attuale",
    rsKeepP: "Resta riservato per Lei finché non sceglie un nuovo orario.",
    rsDoneH: "Il Suo appuntamento è stato spostato.",
    rescheduleP: (d, t) => `Il Suo appuntamento attuale: ${d}, ${t}. Resta riservato per Lei finché non avrà scelto un nuovo orario.`,
    rescheduleBtn: (d, t) => `Sposta a ${d}, ${t}`,
    rescheduledH: (d, t) => `Spostato! Il Suo nuovo appuntamento: ${d}, ${t}.`,
    rescheduledP: "La nuova conferma Le arriva a breve via e-mail.",
    rescheduleGone: "Purtroppo questo orario è appena stato occupato. La preghiamo di sceglierne un altro.",
    rescheduleLoading: "Caricamento degli orari liberi …",
    rescheduleNone: "Al momento online non c’è alcun orario adatto libero. Ci scriva pure su WhatsApp.",
    rescheduleDown: "In questo momento qualcosa non funziona da parte nostra. Riprovi tra poco oppure ci scriva su WhatsApp.",
    rescheduleUnavailable: "Al momento non possiamo verificare gli orari liberi. Il Suo appuntamento attuale resta invariato. Riprovi tra qualche minuto. Oppure ci scriva due righe su WhatsApp.",
  },
  tr: {
    subjectBooked: (d, t) => `Randevu alındı: ${d}, ${t}`,
    subjectRequest: (d, t) => `Randevu talebi: ${d}, ${t}`,
    subjectRescheduled: (d, t) => `Yeni randevu: ${d}, ${t}`,
    subjectCancelled: (d, t) => `İptal edildi: ${d}, ${t}`,
    introCancelled: (d, t) => `${d}, ${t} randevunuz iptal edildi.`,
    bookNewQ: "Yeni bir randevu isterseniz buradan alabilirsiniz:",
    bookNew: "Yeni randevu al",
    subjectReminder: (t) => `Lütfen onaylayın: yarın, ${t}`,
    greeting: (n) => `Merhaba ${n},`,
    introBooked: "Bize geleceğiniz için çok sevindik! Sizi bekliyoruz:",
    introRequest: "Bize gelmek istemenize çok sevindik! Bu saati sizin için ayırdık ve kısa süre içinde WhatsApp üzerinden size yazacağız:",
    introRescheduled: "Randevunuz değiştirildi. Sizi bekliyoruz:",
    mapL: "Yol tarifi",
    punctual: `Zamanınız bizim için değerli: ${BRAND}’de randevunuz zamanında başlar, genellikle hiç beklemeden. Lütfen kararlaştırılan saatte ya da en fazla beş dakika önce gelin. Daha geç gelirseniz, sonraki danışanlarımız da zamanında başlayabilsin diye randevunuza ayrılan süre o kadar kısalır.`,
    both: "İkiniz için de zaman ayırdık.",
    saveQ: "Randevuyu hemen takviminize kaydetmek ister misiniz?",
    gcal: "Google Takvim",
    ical: "iPhone Takvimi",
    ocal: "Outlook",
    oldCalendarNote: "Eski randevuyu takviminize kaydettiyseniz lütfen oradan silin.",
    reminderNote: "Randevudan bir gün önce size bir kez daha hatırlatacağız.",
    cancelInfo: "Randevunuzu bu bağlantı üzerinden 24 saat öncesine kadar değiştirebilir veya iptal edebilirsiniz.",
    manageLink: "Randevuyu değiştir veya iptal et",
    closing: "Görüşmek üzere!",
    introReminder: `Yarın ${BRAND}’de görüşüyoruz, sizi bekliyoruz!`,
    punctualShort: "Randevunuz zamanında başlar, genellikle hiç beklemeden. Lütfen kararlaştırılan saatte ya da en fazla beş dakika önce gelin.",
    confirmQ: "Randevu size hâlâ uygun mu? O zaman lütfen tek tıkla kısaca onaylayın:",
    yes: "Evet, geliyorum",
    notFit: "Yine de uymuyor mu? O zaman randevunuzu buradan değiştirin:",
    rescheduleLink: "Randevuyu değiştir",
    closingReminder: "Yarın görüşmek üzere!",
    icsManage: "Randevuyu görüntüle, değiştir veya iptal et",
    icsWindow: "(24 saat öncesine kadar)",
    pageTitle: "Randevunuz",
    pageIntro: `Burada ${BRAND}’deki randevunuzu görebilirsiniz:`,
    windowOpen: "Randevunuzu 24 saat öncesine kadar değiştirebilir veya iptal edebilirsiniz.",
    windowShort: "Gelemeyecek misiniz? Lütfen bize kısaca haber verin, böylece bu saati başka birine verebiliriz.",
    reschedule: "Randevuyu değiştir",
    cancel: "Randevuyu iptal et",
    cancelShort: "Maalesef gelemiyorum",
    cancelQ: "Randevunuzu iptal etmek istiyor musunuz?",
    cancelYes: "Randevuyu iptal et",
    cancelNo: "Randevuyu koru",
    orReschedule: "Ya da değiştirmeyi mi tercih edersiniz?",
    doneYes: (d, t) => `Teşekkürler! Sizi bekliyoruz: ${d}, ${t}.`,
    doneCancel: "Randevunuz iptal edildi. Sizi başka bir zaman görmekten memnuniyet duyarız.",
    cancelledInfo: "Randevunuz zaten iptal edilmiş. Yeni bir randevu bulmak ister misiniz?",
    past: (d, t) => `Bu randevunun tarihi geçti: ${d}, ${t}. Yeni bir randevu almak ister misiniz?`,
    newBooking: "Yeni randevu al",
    invalid: "Bu bağlantı açılamıyor. Bize kısaca WhatsApp üzerinden yazın, memnuniyetle yardımcı oluruz.",
    waButton: "WhatsApp üzerinden yazın",
    testNote: "Test modu: Bu mesaj bir test rezervasyonuna aittir.",
    rescheduleH: "Yeni bir saat seçin",
    rsHA: "Size hangi zaman", rsHB: "daha uygun?", rsCurrentL: "Mevcut randevunuz",
    rsKeepP: "Yeni bir saat seçene kadar sizin için ayrılmış kalır.",
    rsDoneH: "Randevunuz değiştirildi.",
    rescheduleP: (d, t) => `Mevcut randevunuz: ${d}, ${t}. Yeni bir saat seçene kadar bu randevu sizin için ayrılmış kalır.`,
    rescheduleBtn: (d, t) => `Yeni saat olarak seç: ${d}, ${t}`,
    rescheduledH: (d, t) => `Değiştirildi! Yeni randevunuz: ${d}, ${t}.`,
    rescheduledP: "Yeni onay birazdan e-posta ile size ulaşacak.",
    rescheduleGone: "Bu saat maalesef az önce doldu. Lütfen başka bir saat seçin.",
    rescheduleLoading: "Boş saatler yükleniyor …",
    rescheduleNone: "Şu anda online uygun boş saat yok. Bize WhatsApp üzerinden yazabilirsiniz.",
    rescheduleDown: "Şu anda bizde bir aksaklık var. Lütfen birazdan tekrar deneyin ya da bize WhatsApp üzerinden yazın.",
    rescheduleUnavailable: "Boş saatleri şu anda kontrol edemiyoruz. Mevcut randevunuz değişmeden kalır. Lütfen birkaç dakika sonra tekrar deneyin. Ya da bize kısaca WhatsApp üzerinden yazın.",
  },
  uk: {
    subjectBooked: (d, t) => `Заброньовано: ${d}, ${t}`,
    subjectRequest: (d, t) => `Запит прийнято: ${d}, ${t}`,
    subjectRescheduled: (d, t) => `Перенесено: ${d}, ${t}`,
    subjectCancelled: (d, t) => `Скасовано: ${d}, ${t}`,
    introCancelled: (d, t) => `Ваш запис на ${d}, ${t} скасовано.`,
    bookNewQ: "Якщо бажаєте новий запис, ви можете зробити його тут:",
    bookNew: "Записатися знову",
    subjectReminder: (t) => `Просимо підтвердити: завтра, ${t}`,
    greeting: (n) => `Добрий день, ${n},`,
    introBooked: "Чудово, що Ви до нас завітаєте! Чекаємо на Вас:",
    introRequest: "Чудово, що Ви хочете до нас завітати! Ми зарезервували для Вас цей час і невдовзі напишемо Вам у WhatsApp:",
    introRescheduled: "Ваш запис перенесено. Чекаємо на Вас:",
    mapL: "Як нас знайти",
    punctual: `Ваш час для нас важливий: у ${BRAND} Ваш прийом починається вчасно, як правило, зовсім без очікування. Будь ласка, приходьте у призначений час або щонайбільше за п’ять хвилин до нього. Якщо Ви прийдете пізніше, на Ваш прийом залишиться відповідно менше часу, щоб наступні клієнти теж почали вчасно.`,
    both: "Ми запланували час для Вас обох.",
    saveQ: "Бажаєте одразу зберегти запис у календарі?",
    gcal: "Google Календар",
    ical: "Календар iPhone",
    ocal: "Outlook",
    oldCalendarNote: "Якщо Ви зберегли попередній запис у Вашому календарі, будь ласка, видаліть його там.",
    reminderNote: "За день до прийому ми ще раз Вам нагадаємо.",
    cancelInfo: "Перенести або скасувати запис можна не пізніше ніж за 24 години за цим посиланням.",
    manageLink: "Перенести або скасувати запис",
    closing: "До зустрічі!",
    introReminder: `Завтра ми побачимося в ${BRAND}, чекаємо на Вас!`,
    punctualShort: "Ваш прийом починається вчасно, як правило, зовсім без очікування. Будь ласка, приходьте у призначений час або щонайбільше за п’ять хвилин до нього.",
    confirmQ: "Цей час Вам і надалі підходить? Тоді, будь ласка, коротко підтвердьте одним натисканням:",
    yes: "Так, я прийду",
    notFit: "Все ж не виходить? Тоді перенесіть запис тут:",
    rescheduleLink: "Перенести запис",
    closingReminder: "До завтра!",
    icsManage: "Переглянути, перенести або скасувати запис",
    icsWindow: "(не пізніше ніж за 24 години)",
    pageTitle: "Ваш запис",
    pageIntro: `Тут Ви знайдете Ваш запис у ${BRAND}:`,
    windowOpen: "Перенести або скасувати запис можна не пізніше ніж за 24 години.",
    windowShort: "Не можете прийти? Будь ласка, коротко повідомте нам, тоді ми ще зможемо запропонувати цей час комусь іншому.",
    reschedule: "Перенести запис",
    cancel: "Скасувати запис",
    cancelShort: "На жаль, не зможу",
    cancelQ: "Бажаєте скасувати Ваш запис?",
    cancelYes: "Скасувати запис",
    cancelNo: "Залишити запис",
    orReschedule: "Або краще перенести?",
    doneYes: (d, t) => `Дякуємо! Чекаємо на Вас: ${d}, ${t}.`,
    doneCancel: "Ваш запис скасовано. Будемо раді бачити Вас іншим разом.",
    cancelledInfo: "Ваш запис уже скасовано. Бажаєте знайти новий час?",
    past: (d, t) => `Цей запис уже минув: ${d}, ${t}. Бажаєте домовитися про новий?`,
    newBooking: "Записатися на новий час",
    invalid: "Це посилання не вдається відкрити. Коротко напишіть нам у WhatsApp, ми охоче Вам допоможемо.",
    waButton: "Написати у WhatsApp",
    testNote: "Тестовий режим: це повідомлення стосується тестового бронювання.",
    rescheduleH: "Оберіть новий час",
    rsHA: "Коли Вам", rsHB: "зручніше?", rsCurrentL: "Ваш поточний запис",
    rsKeepP: "Він залишається за Вами, доки Ви не оберете новий час.",
    rsDoneH: "Ваш запис перенесено.",
    rescheduleP: (d, t) => `Ваш поточний запис: ${d}, ${t}. Він залишається за Вами, доки Ви не оберете новий час.`,
    rescheduleBtn: (d, t) => `Перенести: ${d}, ${t}`,
    rescheduledH: (d, t) => `Перенесено! Ваш новий запис: ${d}, ${t}.`,
    rescheduledP: "Нове підтвердження невдовзі надійде на Вашу електронну пошту.",
    rescheduleGone: "На жаль, цей час щойно зайняли. Будь ласка, оберіть інший.",
    rescheduleLoading: "Завантажуємо вільний час …",
    rescheduleNone: "Зараз онлайн немає відповідного вільного часу. Напишіть нам у WhatsApp.",
    rescheduleDown: "У нас зараз технічні труднощі. Будь ласка, спробуйте ще раз трохи згодом або напишіть нам у WhatsApp.",
    rescheduleUnavailable: "Зараз ми не можемо перевірити вільний час. Ваш поточний запис залишається без змін. Будь ласка, спробуйте ще раз за кілька хвилин. Або коротко напишіть нам у WhatsApp.",
  },
  ar: {
    subjectBooked: (d, t) => `محجوز: ${d} ${t}`,
    subjectRequest: (d, t) => `طلبكم: ${d} ${t}`,
    subjectRescheduled: (d, t) => `تعديل: ${d} ${t}`,
    subjectCancelled: (d, t) => `إلغاء: ${d} ${t}`,
    introCancelled: (d, t) => `تم إلغاء موعدكم يوم ${d}، ${t}.`,
    bookNewQ: "إذا رغبتم في موعد جديد، يمكنكم حجزه هنا:",
    bookNew: "حجز موعد جديد",
    subjectReminder: (t) => `يرجى التأكيد: غدًا ${t}`,
    greeting: (n) => `مرحبًا ${n}،`,
    introBooked: "يسعدنا قدومكم إلينا! نتطلع إلى لقائكم:",
    introRequest: "يسعدنا رغبتكم في زيارتنا! لقد حجزنا هذا الوقت لكم مبدئيًا، وسنتواصل معكم قريبًا عبر WhatsApp:",
    introRescheduled: "تم تغيير موعدكم. نتطلع إلى لقائكم:",
    mapL: "الطريق إلينا",
    punctual: `وقتكم مهم بالنسبة لنا: في ${BRAND} يبدأ موعدكم في وقته، وعادةً دون أي انتظار. يرجى الحضور في الموعد المتفق عليه أو قبله بخمس دقائق كحد أقصى. في حال التأخر يقصر وقت موعدكم بالقدر نفسه، حتى يتمكن العملاء التالون أيضًا من البدء في الوقت المحدد.`,
    both: "حجزنا وقتًا يكفي لكليكما.",
    saveQ: "هل ترغبون في حفظ الموعد في التقويم الآن؟",
    gcal: "تقويم Google",
    ical: "تقويم iPhone",
    ocal: "Outlook",
    oldCalendarNote: "إذا كنتم قد حفظتم الموعد السابق في التقويم، يرجى حذفه من هناك.",
    reminderNote: "سنذكّركم مرة أخرى قبل الموعد بيوم.",
    cancelInfo: "يمكن تغيير الموعد أو إلغاؤه حتى 24 ساعة قبله عبر هذا الرابط.",
    manageLink: "تغيير الموعد أو إلغاؤه",
    closing: "إلى اللقاء قريبًا!",
    introReminder: `غدًا نلتقي في ${BRAND}، ونتطلع إلى لقائكم!`,
    punctualShort: "يبدأ موعدكم في وقته، وعادةً دون أي انتظار. يرجى الحضور في الموعد المتفق عليه أو قبله بخمس دقائق كحد أقصى.",
    confirmQ: "هل لا يزال الموعد مناسبًا لكم؟ يرجى التأكيد بنقرة واحدة:",
    yes: "نعم، سأحضر",
    notFit: "لم يعد الموعد مناسبًا؟ يمكن تغييره من هنا:",
    rescheduleLink: "تغيير الموعد",
    closingReminder: "إلى اللقاء غدًا!",
    icsManage: "الاطلاع على الموعد أو تغييره أو إلغاؤه",
    icsWindow: "(حتى 24 ساعة قبل الموعد)",
    pageTitle: "موعدكم",
    pageIntro: `هنا تجدون موعدكم في ${BRAND}:`,
    windowOpen: "يمكن تغيير الموعد أو إلغاؤه حتى 24 ساعة قبله.",
    windowShort: "لا يمكنكم الحضور؟ يرجى إبلاغنا باختصار، حتى نتمكن من منح هذا الوقت لشخص آخر.",
    reschedule: "تغيير الموعد",
    cancel: "إلغاء الموعد",
    cancelShort: "تعذّر الحضور",
    cancelQ: "هل ترغبون في إلغاء موعدكم؟",
    cancelYes: "إلغاء الموعد",
    cancelNo: "الإبقاء على الموعد",
    orReschedule: "أم تفضلون تغيير الموعد؟",
    doneYes: (d, t) => `شكرًا! نتطلع إلى لقائكم يوم ${d}، ${t}.`,
    doneCancel: "تم إلغاء موعدكم. يسعدنا أن نراكم في وقت آخر.",
    cancelledInfo: "تم إلغاء موعدكم مسبقًا. هل ترغبون في اختيار موعد جديد؟",
    past: (d, t) => `كان الموعد يوم ${d}، ${t}. هل ترغبون في تحديد موعد جديد؟`,
    newBooking: "حجز موعد جديد",
    invalid: "تعذّر فتح هذا الرابط. يرجى مراسلتنا عبر WhatsApp، ويسعدنا مساعدتكم.",
    waButton: "المراسلة عبر WhatsApp",
    testNote: "وضع تجريبي: هذه الرسالة تتعلق بحجز تجريبي.",
    rescheduleH: "اختيار وقت جديد",
    rsHA: "متى يناسبكم", rsHB: "أكثر؟", rsCurrentL: "موعدكم الحالي",
    rsKeepP: "يبقى محجوزًا لكم إلى أن تختاروا وقتًا جديدًا.",
    rsDoneH: "تم تعديل موعدكم.",
    rescheduleP: (d, t) => `موعدكم الحالي: ${d}، ${t}. يبقى محجوزًا لكم إلى أن تختاروا وقتًا جديدًا.`,
    rescheduleBtn: (d, t) => `النقل إلى ${d}، ${t}`,
    rescheduledH: (d, t) => `تم التغيير! موعدكم الجديد: ${d}، ${t}.`,
    rescheduledP: "سيصلكم التأكيد الجديد بالبريد الإلكتروني بعد قليل.",
    rescheduleGone: "للأسف حُجز هذا الوقت للتو. يرجى اختيار وقت آخر.",
    rescheduleLoading: "جارٍ تحميل الأوقات المتاحة …",
    rescheduleNone: "لا يوجد حاليًا وقت مناسب متاح عبر الإنترنت. يسعدنا تواصلكم معنا عبر WhatsApp.",
    rescheduleDown: "هناك خلل مؤقت لدينا. يرجى المحاولة مرة أخرى بعد قليل أو مراسلتنا عبر WhatsApp.",
    rescheduleUnavailable: "لا يمكننا التحقق من الأوقات المتاحة حاليًا. يبقى موعدكم الحالي دون تغيير. يرجى المحاولة مرة أخرى بعد بضع دقائق، أو مراسلتنا باختصار عبر WhatsApp.",
  },

};
