/*
 * Texte der Startseite, Entwurf B „Persönlich“ (Vorlage vom 5. Oktober 2026). Deutsch wörtlich aus der Vorlage,
 * von Dr. Vogel einzeln freigegeben; die anderen Sprachen sind daraus übersetzt (Ukrainisch und Arabisch:
 * Muttersprachler-Prüfung offen). Kopfzeile und Fußzeile nutzen dieselben Texte auch auf der Buchungsseite.
 * title und metaDesc bleiben wie bisher (Seitentitel und Linkvorschau unverändert, lib/share-meta.ts).
 * Zwei Teile einer Überschrift: …A normal, …B kursiv in Blau (Newsreader).
 */
import type { Lang } from "./i18n";

export interface HomeTexts {
  title: string;
  metaDesc: string;
  /* Kopfzeile */
  rateLong: string;
  rateShort: string;
  rateAria: string;
  navAria: string;
  navStudio: string;
  navTreat: string;
  navHow: string;
  navFaq: string;
  book: string;
  menu: string;
  /* Start */
  heroEyebrow: string;
  h1A: string;
  h1B: string;
  lead: string;
  googleA: string;
  googleB: string;
  heroAlt: string;
  docRole: string;
  /* Ihr Arzt */
  docHA: string;
  docHB: string;
  handAlt: string;
  quote: string;
  address: string;
  mapL: string;
  studioOpen: string;
  studioClose: string;
  photoConsult: string;
  photoTreat: string;
  photoStudio: string;
  photoEntrance: string;
  /* Für wen */
  whyHA: string;
  whyHB: string;
  why1H: string;
  why1P: string;
  why2H: string;
  why2P: string;
  why3H: string;
  why3P: string;
  why4H: string;
  why4P: string;
  why5H: string;
  why5P: string;
  why6H: string;
  why6P: string;
  /* Behandlungen */
  treatHA: string;
  treatHB: string;
  t1H: string;
  t1D: string;
  t1Alt: string;
  t2H: string;
  t2D: string;
  t2Alt: string;
  t3H: string;
  t3D: string;
  t3Alt: string;
  t4H: string;
  t4D: string;
  t4Alt: string;
  /** „ab 120 €*“ */
  priceFrom: (price: string) => string;
  allPrices: string;
  pZones: string;
  pZone1: string;
  pZone2: string;
  pZone3: string;
  pZoneMore: string;
  pNefD: string;
  pAchselH: string;
  pAchselD: string;
  pLachsH: string;
  pLachs1: string;
  pLachs4: string;
  pnote: string;
  /* Ablauf */
  howHA: string;
  howHB: string;
  s1H: string;
  s1P: string;
  s2H: string;
  s2P: string;
  s3H: string;
  s3P: string;
  /* Bewertungen */
  revHA: string;
  revHB: string;
  allReviews: string;
  /* Fragen */
  faqHA: string;
  faqHB: string;
  q1: string;
  a1: string;
  q2: string;
  a2: string;
  q3: string;
  a3: string;
  q4: string;
  a4: string;
  /* Abschluss und Fußzeile */
  ctaHA: string;
  ctaHB: string;
  copyright: string;
  imprint: string;
  privacy: string;
}

/* Kundenstimmen von Google Maps: Zitate bleiben in der Originalsprache und werden nicht übersetzt */
export const REVIEWS: { text: string; lang: Lang; name: string; initial: string }[] = [
  { text: "„Ich bin selbst Ärztin (…). Bei Dr. Sebastian Vogel habe ich mich von Anfang an sehr gut aufgehoben gefühlt.“", lang: "de", name: "Kathleen", initial: "K" },
  { text: "„Er nimmt sich immer Zeit und hat beim ersten Mal direkt gesehen, dass meine linke Zornesfalte stärker ist als die rechte (…).“", lang: "de", name: "Antje D.", initial: "A" },
  { text: "„Dr. Vogel is a true professional (…). The location is also beautifully designed and makes you feel welcomed immediately.“", lang: "en", name: "Cyril S.", initial: "C" },
];

const de: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Ärztliche Faltenbehandlung in Berlin",
  metaDesc: "PALO SKIN by Dr. Vogel in Berlin Prenzlauer Berg: ärztliche Faltenbehandlung durch Dr. med. Sebastian Vogel. Termine vor und nach der Arbeit und am Wochenende.",
  rateLong: "★ 5,0 Kundenbewertungen",
  rateShort: "★ 5,0",
  rateAria: "5,0 Kundenbewertungen auf Google Maps",
  navAria: "Hauptmenü",
  navStudio: "Studio",
  navTreat: "Behandlungen",
  navHow: "Ablauf",
  navFaq: "Fragen",
  book: "Termin buchen",
  menu: "Menü",
  heroEyebrow: "Berlin Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Ärztliche Faltenbehandlung und Skin Booster. Mitten im Kollwitzkiez.",
  googleA: "5,0",
  googleB: "bei Google",
  heroAlt: "Dr. med. Sebastian Vogel im weißen T-Shirt am Tisch im Studio PALO SKIN in Berlin Prenzlauer Berg",
  docRole: "Arzt und Gründer von PALO SKIN",
  docHA: "Eine ruhige",
  docHB: "Hand.",
  handAlt: "Ruhig übereinanderliegende Hände von Dr. med. Sebastian Vogel auf dem schwarzen Tisch im Studio PALO SKIN in Berlin Prenzlauer Berg",
  quote: "„Ich bin Dr. med. Sebastian Vogel. Ich habe mehrere Jahre in der Chirurgie und in weiteren Fachrichtungen gearbeitet und viele tausend ästhetische Behandlungen durchgeführt. Bei PALO SKIN behandle ich Sie selbst. Mein Ziel sind dezente Ergebnisse, die zu Ihrem Gesicht passen.“",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "So finden Sie uns",
  studioOpen: "Das Studio ansehen",
  studioClose: "Fotos schließen",
  photoConsult: "Beratungsbereich im Studio PALO SKIN in Berlin Prenzlauer Berg: schwarzer Tisch, drei helle Sessel und das blaue Wandobjekt",
  photoTreat: "Behandlungsraum im Studio PALO SKIN in Berlin Prenzlauer Berg mit Behandlungsliege und Holzlamellen",
  photoStudio: "Holzlamellen und blaues Wandobjekt im Studio PALO SKIN in Berlin Prenzlauer Berg",
  photoEntrance: "Schild am Eingang des Studios PALO SKIN in der Hagenauer Straße in Berlin Prenzlauer Berg",
  whyHA: "Für wen ich PALO SKIN",
  whyHB: "gegründet habe.",
  why1H: "Pünktlich statt Wartezimmer.",
  why1P: "Für alle, die ihren Termin in einen vollen Alltag einbauen müssen.",
  why2H: "Kaum Papierkram.",
  why2P: "Für Menschen, die es einfach mögen: Wir fragen nur, was zählt.",
  why3H: "Gemütlich statt klinisch.",
  why3P: "Für diejenigen, die sich auch beim Arzt wohlfühlen möchten.",
  why4H: "Behandlung in Ihrer Sprache.",
  why4P: "Für Berlin und die Welt: Behandlung auf Deutsch, Englisch, Spanisch, Französisch und Portugiesisch.",
  why5H: "Besonders feine Nadeln.",
  why5P: "Für alle, die eine möglichst sanfte Behandlung möchten.",
  why6H: "Nur Originalpräparate.",
  why6P: "Für Menschen, die wissen wollen, was sie bekommen: aus deutschen Apotheken.",
  treatHA: "Genau, was Sie brauchen.",
  treatHB: "Zu fairen Preisen.",
  t1H: "Faltenbehandlung und mehr",
  t1D: "Zornesfalte, Stirn, Krähenfüße und weitere Zonen.",
  t1Alt: "Seidenfalte in Creme, Bildmotiv zur Faltenbehandlung bei PALO SKIN in Berlin Prenzlauer Berg",
  t2H: "Kaumuskel (Masseter)",
  t2D: "Gesichtskontur und Zähneknirschen.",
  t2Alt: "Mann mit geschlossenen Augen, Hand an der Wange, Bildmotiv zur Behandlung des Kaumuskels bei PALO SKIN in Berlin Prenzlauer Berg",
  t3H: "Nefertiti-Lift",
  t3D: "Hals und Kieferkontur.",
  t3Alt: "Helle Steinbüste der Nofretete im Profil, Bildmotiv zum Nefertiti-Lift bei PALO SKIN in Berlin Prenzlauer Berg",
  t4H: "Lachs-DNA",
  t4D: "Polynukleotide für dunkle Augenringe und die Augenpartie.",
  t4Alt: "Augenpartie einer Frau, Bildmotiv zur Behandlung mit Lachs-DNA bei PALO SKIN in Berlin Prenzlauer Berg",
  priceFrom: (p) => `ab ${p}`,
  allPrices: "Alle Preise ansehen",
  pZones: "Faltenbehandlung und mehr",
  pZone1: "1 Zone",
  pZone2: "2 Zonen",
  pZone3: "3 Zonen",
  pZoneMore: "jede weitere Zone",
  pNefD: "Hals und Kieferkontur",
  pAchselH: "Übermäßiges Schwitzen (Hyperhidrose)",
  pAchselD: "Achseln",
  pLachsH: "Lachs-DNA (Polynukleotide)",
  pLachs1: "Eine Behandlung",
  pLachs4: "Vier Behandlungen",
  pnote: "* Richtwerte. Abrechnung nach der Gebührenordnung für Ärzte. Preise inklusive Mehrwertsteuer.",
  howHA: "Erst das Gespräch.",
  howHB: "Dann die Behandlung.",
  s1H: "Wann es Ihnen passt.",
  s1P: "Termine vor und nach der Arbeit und auch am Wochenende. Verschieben können Sie selbst, bis 24 Stunden vorher.",
  s2H: "Eine ausführliche Beratung.",
  s2P: "Was möchten Sie verändern? Wir besprechen Möglichkeiten, Grenzen, Risiken und Kosten.",
  s3H: "Ganz ohne Druck.",
  s3P: "Passt die Behandlung zu Ihnen, ist sie direkt im selben Termin möglich. Und wenn Sie lieber noch einmal nachdenken möchten, sind Sie genauso willkommen.",
  revHA: "Was Kunden",
  revHB: "über uns sagen.",
  allReviews: "Alle Bewertungen auf Google Maps",
  faqHA: "Häufige",
  faqHB: "Fragen.",
  q1: "Was ist eine Zone?",
  a1: "Ein Behandlungsbereich, zum Beispiel Zornesfalte, Stirn oder Krähenfüße (beide Seiten zusammen). Weitere Zonen: Lip Flip, Brow Lift, Mundwinkel, Erdbeerkinn, Gummy Smile, Oberlippenfältchen, Bunny Lines, Nasenverschmälerung.",
  q2: "Wann kann ich wieder zur Arbeit?",
  a2: "Direkt danach. Kleine Rötungen an den Einstichstellen verschwinden in der Regel nach wenigen Minuten. Was Sie danach beachten sollten, besprechen wir vorab.",
  q3: "Wann wirkt die Faltenbehandlung und wie lange hält sie?",
  a3: "Die Wirkung beginnt meist nach zwei bis drei Tagen und ist nach etwa zwei Wochen vollständig. Sie hält in der Regel drei bis sechs Monate, das ist von Mensch zu Mensch verschieden.",
  q4: "Gibt es Gründe, nicht zu behandeln?",
  a4: "Ja, zum Beispiel Schwangerschaft und Stillzeit, bestimmte Muskelerkrankungen, akute Infekte im Behandlungsbereich und bekannte Unverträglichkeiten. Ob die Behandlung für Sie geeignet ist, klären wir vor jeder Behandlung im Gespräch.",
  ctaHA: "Ihr Termin.",
  ctaHB: "Ganz flexibel.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Impressum",
  privacy: "Datenschutz",
};

/* Übersetzungen aus der deutschen Fassung (5. Oktober 2026). Ukrainisch und Arabisch: Muttersprachler-Prüfung offen. */
const en: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Physician-led wrinkle treatment in Berlin",
  metaDesc: "PALO SKIN by Dr. Vogel in Berlin Prenzlauer Berg: physician-led wrinkle treatment by Dr. med. Sebastian Vogel. Open before and after work and at weekends.",
  rateLong: "★ 5.0 client rating",
  rateShort: "★ 5.0",
  rateAria: "5.0 client rating on Google Maps",
  navAria: "Main menu",
  navStudio: "Studio",
  navTreat: "Treatments",
  navHow: "How it works",
  navFaq: "Questions",
  book: "Book appointment",
  menu: "Menu",
  heroEyebrow: "Berlin Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Physician-led wrinkle treatment and Skin Booster. Right in the Kollwitzkiez.",
  googleA: "5.0",
  googleB: "on Google",
  heroAlt: "Dr. med. Sebastian Vogel in a white T-shirt at the table in the PALO SKIN studio in Berlin Prenzlauer Berg",
  docRole: "Physician and founder of PALO SKIN",
  docHA: "A steady",
  docHB: "hand.",
  handAlt: "Dr. med. Sebastian Vogel’s hands resting calmly on top of each other on the black table in the PALO SKIN studio in Berlin Prenzlauer Berg",
  quote: "“I am Dr. med. Sebastian Vogel. I worked for several years in surgery and other specialities, and I have performed many thousands of aesthetic treatments. At PALO SKIN, I treat you myself. My aim is subtle results that suit your face.”",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "How to find us",
  studioOpen: "See the studio",
  studioClose: "Close photos",
  photoConsult: "Consultation area in the PALO SKIN studio in Berlin Prenzlauer Berg: black table, three light armchairs and the blue wall piece",
  photoTreat: "Treatment room in the PALO SKIN studio in Berlin Prenzlauer Berg with treatment chair and wooden slats",
  photoStudio: "Wooden slats and blue wall piece in the PALO SKIN studio in Berlin Prenzlauer Berg",
  photoEntrance: "Sign at the entrance of the PALO SKIN studio on Hagenauer Straße in Berlin Prenzlauer Berg",
  whyHA: "Who I founded PALO SKIN",
  whyHB: "for.",
  why1H: "On time, no waiting room.",
  why1P: "For everyone who has to fit their appointment into a busy everyday life.",
  why2H: "Hardly any paperwork.",
  why2P: "For people who like things simple: we only ask what matters.",
  why3H: "Cosy, not clinical.",
  why3P: "For those who want to feel at ease, even at the doctor’s.",
  why4H: "Treatment in your language.",
  why4P: "For Berlin and the world: treatment in German, English, Spanish, French and Portuguese.",
  why5H: "Especially fine needles.",
  why5P: "For everyone who would like the gentlest possible treatment.",
  why6H: "Original products only.",
  why6P: "For people who want to know what they are getting: from German pharmacies.",
  treatHA: "Exactly what you need.",
  treatHB: "At fair prices.",
  t1H: "Wrinkle treatment and more",
  t1D: "Frown lines, forehead, crow’s feet and other zones.",
  t1Alt: "Fold of cream-coloured silk, image for wrinkle treatment at PALO SKIN in Berlin Prenzlauer Berg",
  t2H: "Jaw muscle (masseter)",
  t2D: "Facial contour and teeth grinding.",
  t2Alt: "Man with his eyes closed, hand on his cheek, image for jaw muscle treatment at PALO SKIN in Berlin Prenzlauer Berg",
  t3H: "Nefertiti lift",
  t3D: "Neck and jawline.",
  t3Alt: "Pale stone bust of Nefertiti in profile, image for the Nefertiti lift at PALO SKIN in Berlin Prenzlauer Berg",
  t4H: "Salmon DNA",
  t4D: "Polynucleotides for dark circles and the eye area.",
  t4Alt: "A woman’s eye area, image for salmon DNA treatment at PALO SKIN in Berlin Prenzlauer Berg",
  priceFrom: (p) => `from ${p}`,
  allPrices: "See all prices",
  pZones: "Wrinkle treatment and more",
  pZone1: "1 zone",
  pZone2: "2 zones",
  pZone3: "3 zones",
  pZoneMore: "each additional zone",
  pNefD: "Neck and jawline",
  pAchselH: "Excessive sweating (hyperhidrosis)",
  pAchselD: "Underarms",
  pLachsH: "Salmon DNA (polynucleotides)",
  pLachs1: "One treatment",
  pLachs4: "Four treatments",
  pnote: "* Guide prices. Billed according to the German fee schedule for physicians (Gebührenordnung für Ärzte). Prices include value added tax.",
  howHA: "First we talk.",
  howHB: "Then the treatment.",
  s1H: "Whenever suits you.",
  s1P: "Appointments before and after work, and at weekends too. You can reschedule yourself up to 24 hours in advance.",
  s2H: "A thorough consultation.",
  s2P: "What would you like to change? We discuss the options, limits, risks and costs.",
  s3H: "No pressure at all.",
  s3P: "If the treatment suits you, it can be done in the same appointment. And if you would rather think it over, you are just as welcome.",
  revHA: "What clients",
  revHB: "say about us.",
  allReviews: "All reviews on Google Maps",
  faqHA: "Common",
  faqHB: "questions.",
  q1: "What is a zone?",
  a1: "A treatment area, for example the frown lines, forehead or crow’s feet (both sides together). Further zones: Lip Flip, Brow Lift, mouth corners, dimpled chin, Gummy Smile, upper lip lines, Bunny Lines, nose slimming.",
  q2: "When can I go back to work?",
  a2: "Straight away. Small red marks at the injection points usually disappear within a few minutes. We talk beforehand about what to bear in mind afterwards.",
  q3: "When does the wrinkle treatment take effect, and how long does it last?",
  a3: "The effect usually begins after two to three days and is complete after about two weeks. It generally lasts three to six months, which varies from person to person.",
  q4: "Are there reasons not to treat?",
  a4: "Yes, for example pregnancy and breastfeeding, certain muscle disorders, acute infections in the treatment area and known intolerances. Before every treatment, we talk through whether it is suitable for you.",
  ctaHA: "Your visit.",
  ctaHB: "Fully flexible.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Legal notice",
  privacy: "Privacy",
};

const es: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Tratamiento médico de arrugas en Berlín",
  metaDesc: "PALO SKIN by Dr. Vogel en Berlín Prenzlauer Berg: tratamiento médico de arrugas del Dr. med. Sebastian Vogel. Citas antes y tras el trabajo y el fin de semana.",
  rateLong: "★ 5,0 en valoraciones de clientes",
  rateShort: "★ 5,0",
  rateAria: "Valoración de clientes de 5,0 en Google Maps",
  navAria: "Menú principal",
  navStudio: "Estudio",
  navTreat: "Tratamientos",
  navHow: "Cómo funciona",
  navFaq: "Preguntas",
  book: "Reservar cita",
  menu: "Menú",
  heroEyebrow: "Berlín Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Tratamiento médico de arrugas y Skin Booster. En pleno Kollwitzkiez.",
  googleA: "5,0",
  googleB: "en Google",
  heroAlt: "El Dr. med. Sebastian Vogel con camiseta blanca, sentado a la mesa en el estudio PALO SKIN de Berlín Prenzlauer Berg",
  docRole: "Médico y fundador de PALO SKIN",
  docHA: "Una mano",
  docHB: "serena.",
  handAlt: "Las manos del Dr. med. Sebastian Vogel, cruzadas con calma sobre la mesa negra del estudio PALO SKIN en Berlín Prenzlauer Berg",
  quote: "«Soy el Dr. med. Sebastian Vogel. He trabajado varios años en cirugía y en otras especialidades y he realizado miles de tratamientos estéticos. En PALO SKIN le trato yo personalmente. Mi objetivo son resultados discretos, acordes con su rostro.»",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Cómo llegar",
  studioOpen: "Ver el estudio",
  studioClose: "Cerrar las fotos",
  photoConsult: "Zona de asesoramiento del estudio PALO SKIN en Berlín Prenzlauer Berg: mesa negra, tres sillones claros y la pieza azul de la pared",
  photoTreat: "Sala de tratamiento del estudio PALO SKIN en Berlín Prenzlauer Berg, con camilla de tratamiento y listones de madera",
  photoStudio: "Listones de madera y pieza azul en la pared del estudio PALO SKIN en Berlín Prenzlauer Berg",
  photoEntrance: "Placa en la entrada del estudio PALO SKIN, en la Hagenauer Straße de Berlín Prenzlauer Berg",
  whyHA: "Para quién he creado",
  whyHB: "PALO SKIN.",
  why1H: "Puntualidad, sin sala de espera.",
  why1P: "Para quienes tienen que encajar su cita en un día a día muy lleno.",
  why2H: "Apenas papeleo.",
  why2P: "Para quienes prefieren lo sencillo: solo preguntamos lo que importa.",
  why3H: "Acogedor, no clínico.",
  why3P: "Para quienes quieren sentirse a gusto también al ir al médico.",
  why4H: "Tratamiento en su idioma.",
  why4P: "Para Berlín y el mundo: tratamiento en alemán, inglés, español, francés y portugués.",
  why5H: "Agujas especialmente finas.",
  why5P: "Para quienes desean un tratamiento lo más suave posible.",
  why6H: "Solo preparados originales.",
  why6P: "Para quienes quieren saber qué reciben: de farmacias alemanas.",
  treatHA: "Exactamente lo que necesita.",
  treatHB: "A precios justos.",
  t1H: "Tratamiento de arrugas y más",
  t1D: "Entrecejo, frente, patas de gallo y otras zonas.",
  t1Alt: "Pliegue de seda en color crema, imagen del tratamiento de arrugas en PALO SKIN, Berlín Prenzlauer Berg",
  t2H: "Masetero (músculo de la mandíbula)",
  t2D: "Contorno facial y bruxismo.",
  t2Alt: "Hombre con los ojos cerrados y la mano en la mejilla, imagen del tratamiento del masetero en PALO SKIN, Berlín Prenzlauer Berg",
  t3H: "Lifting Nefertiti",
  t3D: "Cuello y contorno mandibular.",
  t3Alt: "Busto de piedra clara de Nefertiti de perfil, imagen del lifting Nefertiti en PALO SKIN, Berlín Prenzlauer Berg",
  t4H: "ADN de salmón",
  t4D: "Polinucleótidos para las ojeras y el contorno de ojos.",
  t4Alt: "Contorno de ojos de una mujer, imagen del tratamiento con ADN de salmón en PALO SKIN, Berlín Prenzlauer Berg",
  priceFrom: (p) => `desde ${p}`,
  allPrices: "Ver todos los precios",
  pZones: "Tratamiento de arrugas y más",
  pZone1: "1 zona",
  pZone2: "2 zonas",
  pZone3: "3 zonas",
  pZoneMore: "cada zona adicional",
  pNefD: "Cuello y contorno mandibular",
  pAchselH: "Sudoración excesiva (hiperhidrosis)",
  pAchselD: "Axilas",
  pLachsH: "ADN de salmón (polinucleótidos)",
  pLachs1: "Un tratamiento",
  pLachs4: "Cuatro tratamientos",
  pnote: "* Precios orientativos. Facturación según el baremo alemán de honorarios médicos (Gebührenordnung für Ärzte). Precios con el impuesto sobre el valor añadido incluido.",
  howHA: "Primero hablamos.",
  howHB: "Después, el tratamiento.",
  s1H: "Cuando le venga bien.",
  s1P: "Citas antes y después del trabajo, y también los fines de semana. Puede cambiar la cita por su cuenta hasta 24 horas antes.",
  s2H: "Un asesoramiento detallado.",
  s2P: "¿Qué le gustaría cambiar? Hablamos de las posibilidades, los límites, los riesgos y los costes.",
  s3H: "Sin ninguna presión.",
  s3P: "Si el tratamiento es adecuado para usted, puede hacerse en la misma cita. Y si prefiere pensarlo con calma, le recibimos con el mismo gusto.",
  revHA: "Qué dicen",
  revHB: "nuestros clientes.",
  allReviews: "Todas las opiniones en Google Maps",
  faqHA: "Dudas",
  faqHB: "frecuentes.",
  q1: "¿Qué es una zona?",
  a1: "Una zona de tratamiento, por ejemplo el entrecejo, la frente o las patas de gallo (ambos lados juntos). Otras zonas: Lip Flip, Brow Lift, comisuras de la boca, mentón en piel de naranja, Gummy Smile, arrugas del labio superior, Bunny Lines, afinado de la nariz.",
  q2: "¿Cuándo puedo volver al trabajo?",
  a2: "Justo después. Las pequeñas rojeces en los puntos de inyección suelen desaparecer en pocos minutos. Lo que debe tener en cuenta después lo hablamos de antemano.",
  q3: "¿Cuándo hace efecto el tratamiento de arrugas y cuánto dura?",
  a3: "El efecto suele empezar a los dos o tres días y es completo a las dos semanas aproximadamente. Por lo general dura de tres a seis meses, según cada persona.",
  q4: "¿Hay motivos para no tratar?",
  a4: "Sí, por ejemplo el embarazo y la lactancia, ciertas enfermedades musculares, infecciones agudas en la zona de tratamiento e intolerancias conocidas. Antes de cada tratamiento aclaramos en la conversación si es adecuado para usted.",
  ctaHA: "Su cita.",
  ctaHB: "Totalmente flexible.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Aviso legal",
  privacy: "Privacidad",
};

const fr: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Traitement médical des rides à Berlin",
  metaDesc: "PALO SKIN by Dr. Vogel à Berlin Prenzlauer Berg : traitement médical des rides du Dr med. Sebastian Vogel. Créneaux avant et après le travail et le week-end.",
  rateLong: "★ 5,0 avis clients",
  rateShort: "★ 5,0",
  rateAria: "Note de 5,0 dans les avis clients sur Google Maps",
  navAria: "Menu principal",
  navStudio: "Studio",
  navTreat: "Soins",
  navHow: "Déroulement",
  navFaq: "Questions",
  book: "Prendre rendez-vous",
  menu: "Menu",
  heroEyebrow: "Berlin Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Traitement médical des rides et Skin Booster. Au cœur du Kollwitzkiez.",
  googleA: "5,0",
  googleB: "sur Google",
  heroAlt: "Le Dr. med. Sebastian Vogel en t-shirt blanc, à la table du studio PALO SKIN à Berlin Prenzlauer Berg",
  docRole: "Médecin et fondateur de PALO SKIN",
  docHA: "Une main",
  docHB: "sûre.",
  handAlt: "Les mains du Dr. med. Sebastian Vogel posées calmement l’une sur l’autre sur la table noire du studio PALO SKIN à Berlin Prenzlauer Berg",
  quote: "« Je suis le Dr. med. Sebastian Vogel. J’ai travaillé plusieurs années en chirurgie et dans d’autres spécialités, et j’ai réalisé des milliers de soins esthétiques. Chez PALO SKIN, c’est moi qui vous soigne. Mon objectif : des résultats discrets, en accord avec votre visage. »",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Comment nous trouver",
  studioOpen: "Découvrir le studio",
  studioClose: "Fermer les photos",
  photoConsult: "Espace de consultation du studio PALO SKIN à Berlin Prenzlauer Berg : table noire, trois fauteuils clairs et l’œuvre murale bleue",
  photoTreat: "Salle de soin du studio PALO SKIN à Berlin Prenzlauer Berg, avec fauteuil de soin et lamelles de bois",
  photoStudio: "Lamelles de bois et œuvre murale bleue au studio PALO SKIN à Berlin Prenzlauer Berg",
  photoEntrance: "Plaque à l’entrée du studio PALO SKIN, Hagenauer Straße, à Berlin Prenzlauer Berg",
  whyHA: "Pour qui j’ai fondé",
  whyHB: "PALO SKIN.",
  why1H: "À l’heure, sans salle d’attente.",
  why1P: "Pour toutes celles et tous ceux qui glissent leur rendez-vous dans un quotidien bien rempli.",
  why2H: "Peu de paperasse.",
  why2P: "Pour les personnes qui aiment la simplicité : nous ne demandons que l’essentiel.",
  why3H: "Chaleureux plutôt qu’aseptisé.",
  why3P: "Pour celles et ceux qui veulent se sentir bien, même chez le médecin.",
  why4H: "Un soin dans votre langue.",
  why4P: "Pour Berlin et le monde entier : soins en allemand, anglais, espagnol, français et portugais.",
  why5H: "Des aiguilles très fines.",
  why5P: "Pour toutes celles et tous ceux qui souhaitent un soin aussi doux que possible.",
  why6H: "Uniquement des produits originaux.",
  why6P: "Pour les personnes qui veulent savoir ce qu’elles reçoivent : des produits issus de pharmacies allemandes.",
  treatHA: "Exactement ce qu’il vous faut.",
  treatHB: "Au juste prix.",
  t1H: "Traitement des rides et plus",
  t1D: "Ride du lion, front, pattes d’oie et autres zones.",
  t1Alt: "Pli de soie couleur crème, image du traitement des rides chez PALO SKIN à Berlin Prenzlauer Berg",
  t2H: "Masséter (muscle de la mâchoire)",
  t2D: "Contour du visage et grincement des dents.",
  t2Alt: "Homme les yeux fermés, la main sur la joue, image du traitement du masséter chez PALO SKIN à Berlin Prenzlauer Berg",
  t3H: "Lifting Néfertiti",
  t3D: "Cou et contour de la mâchoire.",
  t3Alt: "Buste clair en pierre de Néfertiti, de profil, image du lifting Néfertiti chez PALO SKIN à Berlin Prenzlauer Berg",
  t4H: "ADN de saumon",
  t4D: "Polynucléotides pour les cernes et le contour des yeux.",
  t4Alt: "Contour des yeux d’une femme, image du soin à l’ADN de saumon chez PALO SKIN à Berlin Prenzlauer Berg",
  priceFrom: (p) => `à partir de ${p}`,
  allPrices: "Voir tous les tarifs",
  pZones: "Traitement des rides et plus",
  pZone1: "1 zone",
  pZone2: "2 zones",
  pZone3: "3 zones",
  pZoneMore: "chaque zone supplémentaire",
  pNefD: "Cou et contour de la mâchoire",
  pAchselH: "Transpiration excessive (hyperhidrose)",
  pAchselD: "Aisselles",
  pLachsH: "ADN de saumon (polynucléotides)",
  pLachs1: "Une séance",
  pLachs4: "Quatre séances",
  pnote: "* Prix indicatifs. Facturation selon le barème allemand des honoraires médicaux (Gebührenordnung für Ärzte). Prix taxe sur la valeur ajoutée comprise.",
  howHA: "D’abord, l’échange.",
  howHB: "Ensuite, le soin.",
  s1H: "Quand cela vous convient.",
  s1P: "Des rendez-vous avant et après le travail, et aussi le week-end. Vous pouvez déplacer votre rendez-vous vous-même jusqu’à 24 heures avant.",
  s2H: "Une consultation approfondie.",
  s2P: "Que souhaitez-vous changer ? Nous parlons des possibilités, des limites, des risques et des coûts.",
  s3H: "Sans aucune pression.",
  s3P: "Si le soin vous convient, il peut avoir lieu directement lors du même rendez-vous. Et si vous préférez y réfléchir encore, nous vous accueillons tout aussi volontiers.",
  revHA: "Ce que disent",
  revHB: "nos clients.",
  allReviews: "Tous les avis sur Google Maps",
  faqHA: "Vos",
  faqHB: "questions.",
  q1: "Qu’est-ce qu’une zone ?",
  a1: "Une zone de traitement, par exemple la ride du lion, le front ou les pattes d’oie (les deux côtés ensemble). Autres zones : Lip Flip, Brow Lift, coins de la bouche, menton en peau d’orange, Gummy Smile, ridules de la lèvre supérieure, Bunny Lines, affinement du nez.",
  q2: "Quand puis-je retourner au travail ?",
  a2: "Juste après. Les petites rougeurs aux points d’injection disparaissent en général en quelques minutes. Nous voyons ensemble à l’avance à quoi faire attention ensuite.",
  q3: "Quand le traitement des rides agit-il et combien de temps dure-t-il ?",
  a3: "L’effet apparaît le plus souvent après deux à trois jours et est complet après environ deux semaines. Il dure en général de trois à six mois, cela varie d’une personne à l’autre.",
  q4: "Y a-t-il des cas où l’on ne traite pas ?",
  a4: "Oui, par exemple la grossesse et l’allaitement, certaines maladies musculaires, des infections aiguës dans la zone à traiter et des intolérances connues. Avant chaque soin, nous vérifions ensemble lors de l’entretien si ce traitement vous convient.",
  ctaHA: "Votre créneau.",
  ctaHB: "À la carte.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Mentions légales",
  privacy: "Confidentialité",
};

const pt: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Tratamento médico de rugas em Berlim",
  metaDesc: "PALO SKIN by Dr. Vogel em Berlim Prenzlauer Berg: tratamento médico de rugas pelo Dr. med. Sebastian Vogel. Horários antes e após o trabalho e no fim de semana.",
  rateLong: "★ 5,0 nas avaliações de clientes",
  rateShort: "★ 5,0",
  rateAria: "5,0 nas avaliações de clientes no Google Maps",
  navAria: "Menu principal",
  navStudio: "Estúdio",
  navTreat: "Tratamentos",
  navHow: "Como funciona",
  navFaq: "Perguntas",
  book: "Agendar",
  menu: "Menu",
  heroEyebrow: "Berlim Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Tratamento médico de rugas e Skin Booster. No coração do Kollwitzkiez.",
  googleA: "5,0",
  googleB: "no Google",
  heroAlt: "Dr. med. Sebastian Vogel de camiseta branca, à mesa no estúdio PALO SKIN em Berlim Prenzlauer Berg",
  docRole: "Médico e fundador da PALO SKIN",
  docHA: "Uma mão",
  docHB: "firme.",
  handAlt: "Mãos do Dr. med. Sebastian Vogel pousadas calmamente uma sobre a outra na mesa preta do estúdio PALO SKIN em Berlim Prenzlauer Berg",
  quote: "“Sou o Dr. med. Sebastian Vogel. Trabalhei vários anos em cirurgia e em outras especialidades e realizei muitos milhares de tratamentos estéticos. Na PALO SKIN, eu mesmo cuido do seu tratamento. Meu objetivo são resultados discretos, que combinem com o seu rosto.”",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Como chegar",
  studioOpen: "Ver o estúdio",
  studioClose: "Fechar fotos",
  photoConsult: "Área de consulta do estúdio PALO SKIN em Berlim Prenzlauer Berg: mesa preta, três poltronas claras e a peça azul na parede",
  photoTreat: "Sala de tratamento do estúdio PALO SKIN em Berlim Prenzlauer Berg, com cadeira de tratamento e ripas de madeira",
  photoStudio: "Ripas de madeira e peça azul na parede do estúdio PALO SKIN em Berlim Prenzlauer Berg",
  photoEntrance: "Placa na entrada do estúdio PALO SKIN, na Hagenauer Straße, em Berlim Prenzlauer Berg",
  whyHA: "Para quem eu fundei",
  whyHB: "a PALO SKIN.",
  why1H: "Pontual, sem sala de espera.",
  why1P: "Para quem precisa encaixar a consulta em um dia a dia cheio.",
  why2H: "Pouca papelada.",
  why2P: "Para quem gosta de simplicidade: perguntamos só o que importa.",
  why3H: "Aconchegante, não clínico.",
  why3P: "Para quem também quer se sentir à vontade no médico.",
  why4H: "Atendimento no seu idioma.",
  why4P: "Para Berlim e para o mundo: atendimento em alemão, inglês, espanhol, francês e português.",
  why5H: "Agulhas especialmente finas.",
  why5P: "Para quem deseja um tratamento o mais suave possível.",
  why6H: "Somente produtos originais.",
  why6P: "Para quem quer saber o que está recebendo: de farmácias alemãs.",
  treatHA: "Exatamente o que você precisa.",
  treatHB: "A preços justos.",
  t1H: "Tratamento de rugas e mais",
  t1D: "Ruga entre as sobrancelhas, testa, pés de galinha e outras zonas.",
  t1Alt: "Dobra de seda em tom creme, imagem do tratamento de rugas na PALO SKIN em Berlim Prenzlauer Berg",
  t2H: "Masseter (músculo da mandíbula)",
  t2D: "Contorno do rosto e bruxismo.",
  t2Alt: "Homem de olhos fechados, com a mão na bochecha, imagem do tratamento do masseter na PALO SKIN em Berlim Prenzlauer Berg",
  t3H: "Lifting Nefertiti",
  t3D: "Pescoço e contorno da mandíbula.",
  t3Alt: "Busto claro de pedra de Nefertiti, de perfil, imagem do lifting Nefertiti na PALO SKIN em Berlim Prenzlauer Berg",
  t4H: "DNA de salmão",
  t4D: "Polinucleotídeos para olheiras e a área dos olhos.",
  t4Alt: "Área dos olhos de uma mulher, imagem do tratamento com DNA de salmão na PALO SKIN em Berlim Prenzlauer Berg",
  priceFrom: (p) => `a partir de ${p}`,
  allPrices: "Ver todos os preços",
  pZones: "Tratamento de rugas e mais",
  pZone1: "1 zona",
  pZone2: "2 zonas",
  pZone3: "3 zonas",
  pZoneMore: "cada zona adicional",
  pNefD: "Pescoço e contorno da mandíbula",
  pAchselH: "Suor excessivo (hiperidrose)",
  pAchselD: "Axilas",
  pLachsH: "DNA de salmão (polinucleotídeos)",
  pLachs1: "Uma sessão",
  pLachs4: "Quatro sessões",
  pnote: "* Valores de referência. Cobrança conforme a tabela alemã de honorários médicos (Gebührenordnung für Ärzte). Preços com imposto sobre o valor agregado incluído.",
  howHA: "Primeiro, a conversa.",
  howHB: "Depois, o tratamento.",
  s1H: "Quando for melhor para você.",
  s1P: "Horários antes e depois do trabalho e também aos fins de semana. Você pode remarcar por conta própria até 24 horas antes.",
  s2H: "Uma consulta detalhada.",
  s2P: "O que você gostaria de mudar? Falamos sobre possibilidades, limites, riscos e custos.",
  s3H: "Sem nenhuma pressão.",
  s3P: "Se o tratamento for adequado para você, ele pode ser feito na mesma consulta. E se você preferir pensar mais um pouco, receberemos você com o mesmo prazer.",
  revHA: "O que dizem",
  revHB: "sobre nós.",
  allReviews: "Todas as avaliações no Google Maps",
  faqHA: "Dúvidas",
  faqHB: "comuns.",
  q1: "O que é uma zona?",
  a1: "Uma área de tratamento, por exemplo a ruga entre as sobrancelhas, a testa ou os pés de galinha (os dois lados juntos). Outras zonas: Lip Flip, Brow Lift, cantos da boca, queixo em casca de laranja, Gummy Smile, rugas do lábio superior, Bunny Lines, afinamento do nariz.",
  q2: "Quando posso voltar ao trabalho?",
  a2: "Logo em seguida. Pequenas vermelhidões nos pontos de aplicação costumam desaparecer em poucos minutos. O que observar depois, conversamos com você antes.",
  q3: "Quando o tratamento de rugas faz efeito e quanto tempo dura?",
  a3: "O efeito costuma começar após dois a três dias e se completa em cerca de duas semanas. Em geral, dura de três a seis meses, o que varia de pessoa para pessoa.",
  q4: "Há motivos para não fazer o tratamento?",
  a4: "Sim, por exemplo gravidez e amamentação, certas doenças musculares, infecções agudas na área de tratamento e intolerâncias conhecidas. Antes de cada tratamento, esclarecemos na conversa se ele é adequado para você.",
  ctaHA: "Sua consulta.",
  ctaHB: "Bem flexível.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Informações legais",
  privacy: "Privacidade",
};

const it: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Trattamento medico delle rughe a Berlino",
  metaDesc: "PALO SKIN by Dr. Vogel a Berlino Prenzlauer Berg: trattamento medico delle rughe con il Dr. med. Sebastian Vogel. Orari prima e dopo il lavoro e nel weekend.",
  rateLong: "★ 5,0 nelle recensioni dei clienti",
  rateShort: "★ 5,0",
  rateAria: "5,0 nelle recensioni dei clienti su Google Maps",
  navAria: "Menu principale",
  navStudio: "Studio",
  navTreat: "Trattamenti",
  navHow: "Come funziona",
  navFaq: "Domande",
  book: "Prenota",
  menu: "Menu",
  heroEyebrow: "Berlino Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Trattamento medico delle rughe e Skin Booster. Nel cuore del Kollwitzkiez.",
  googleA: "5,0",
  googleB: "su Google",
  heroAlt: "Il Dr. med. Sebastian Vogel in maglietta bianca, seduto al tavolo nello studio PALO SKIN a Berlino Prenzlauer Berg",
  docRole: "Medico e fondatore di PALO SKIN",
  docHA: "Una mano",
  docHB: "ferma.",
  handAlt: "Le mani del Dr. med. Sebastian Vogel, posate con calma l’una sull’altra sul tavolo nero dello studio PALO SKIN a Berlino Prenzlauer Berg",
  quote: "«Sono il Dr. med. Sebastian Vogel. Ho lavorato per diversi anni in chirurgia e in altre specialità e ho eseguito molte migliaia di trattamenti estetici. Da PALO SKIN mi occupo io personalmente del Suo trattamento. Il mio obiettivo sono risultati discreti, in armonia con il Suo viso.»",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Come raggiungerci",
  studioOpen: "Scopra lo studio",
  studioClose: "Chiudi le foto",
  photoConsult: "Zona consulenza dello studio PALO SKIN a Berlino Prenzlauer Berg: tavolo nero, tre poltroncine chiare e l’opera blu alla parete",
  photoTreat: "Sala trattamenti dello studio PALO SKIN a Berlino Prenzlauer Berg, con lettino e listelli di legno",
  photoStudio: "Listelli di legno e opera blu alla parete nello studio PALO SKIN a Berlino Prenzlauer Berg",
  photoEntrance: "Targa all’ingresso dello studio PALO SKIN in Hagenauer Straße, a Berlino Prenzlauer Berg",
  whyHA: "Per chi ho fondato",
  whyHB: "PALO SKIN.",
  why1H: "Puntualità invece della sala d’attesa.",
  why1P: "Per chi deve inserire l’appuntamento in una giornata piena.",
  why2H: "Pochissime scartoffie.",
  why2P: "Per chi ama le cose semplici: chiediamo solo ciò che conta.",
  why3H: "Accogliente, non clinico.",
  why3P: "Per chi vuole sentirsi a proprio agio anche dal medico.",
  why4H: "Trattamento in una lingua che Lei capisce.",
  why4P: "Per Berlino e il mondo: trattamento in tedesco, inglese, spagnolo, francese o portoghese.",
  why5H: "Aghi particolarmente sottili.",
  why5P: "Per chi desidera un trattamento il più delicato possibile.",
  why6H: "Solo preparati originali.",
  why6P: "Per chi vuole sapere che cosa riceve: da farmacie tedesche.",
  treatHA: "Esattamente ciò di cui ha bisogno.",
  treatHB: "A prezzi equi.",
  t1H: "Trattamento delle rughe e altro",
  t1D: "Ruga del leone, fronte, zampe di gallina e altre zone.",
  t1Alt: "Piega di seta color crema, immagine del trattamento delle rughe da PALO SKIN a Berlino Prenzlauer Berg",
  t2H: "Massetere (muscolo della masticazione)",
  t2D: "Contorno del viso e bruxismo.",
  t2Alt: "Uomo con gli occhi chiusi, la mano sulla guancia, immagine del trattamento del massetere da PALO SKIN a Berlino Prenzlauer Berg",
  t3H: "Nefertiti lift",
  t3D: "Collo e linea della mandibola.",
  t3Alt: "Busto in pietra chiara di Nefertiti, di profilo, immagine del Nefertiti lift da PALO SKIN a Berlino Prenzlauer Berg",
  t4H: "DNA di salmone",
  t4D: "Polinucleotidi per le occhiaie scure e il contorno occhi.",
  t4Alt: "Contorno occhi di una donna, immagine del trattamento con DNA di salmone da PALO SKIN a Berlino Prenzlauer Berg",
  priceFrom: (p) => `da ${p}`,
  allPrices: "Tutti i prezzi",
  pZones: "Trattamento delle rughe e altro",
  pZone1: "1 zona",
  pZone2: "2 zone",
  pZone3: "3 zone",
  pZoneMore: "ogni zona aggiuntiva",
  pNefD: "Collo e linea della mandibola",
  pAchselH: "Sudorazione eccessiva (iperidrosi)",
  pAchselD: "Ascelle",
  pLachsH: "DNA di salmone (polinucleotidi)",
  pLachs1: "Un trattamento",
  pLachs4: "Quattro trattamenti",
  pnote: "* Prezzi indicativi. Fatturazione secondo il tariffario tedesco degli onorari medici (Gebührenordnung für Ärzte). Prezzi comprensivi di imposta sul valore aggiunto.",
  howHA: "Prima il colloquio.",
  howHB: "Poi il trattamento.",
  s1H: "Quando Le è più comodo.",
  s1P: "Appuntamenti prima e dopo il lavoro e anche nel fine settimana. Può spostare l’appuntamento in autonomia fino a 24 ore prima.",
  s2H: "Una consulenza approfondita.",
  s2P: "Che cosa vorrebbe cambiare? Parliamo di possibilità, limiti, rischi e costi.",
  s3H: "Senza alcuna pressione.",
  s3P: "Se il trattamento fa per Lei, è possibile farlo subito nello stesso appuntamento. E se preferisce pensarci ancora, La accogliamo altrettanto volentieri.",
  revHA: "Che cosa dicono",
  revHB: "i nostri clienti.",
  allReviews: "Tutte le recensioni su Google Maps",
  faqHA: "Domande",
  faqHB: "frequenti.",
  q1: "Che cos’è una zona?",
  a1: "Un’area di trattamento, per esempio la ruga del leone, la fronte o le zampe di gallina (entrambi i lati insieme). Altre zone: Lip Flip, Brow Lift, angoli della bocca, mento a buccia d’arancia, Gummy Smile, rughe del labbro superiore, Bunny Lines, assottigliamento del naso.",
  q2: "Quando posso tornare al lavoro?",
  a2: "Subito dopo. Piccoli arrossamenti nei punti di iniezione di solito scompaiono in pochi minuti. A che cosa prestare attenzione dopo il trattamento, ne parliamo prima.",
  q3: "Quando fa effetto il trattamento delle rughe e quanto dura?",
  a3: "L’effetto inizia di solito dopo due o tre giorni ed è completo dopo circa due settimane. In genere dura da tre a sei mesi, ma varia da persona a persona.",
  q4: "Ci sono motivi per non trattare?",
  a4: "Sì, per esempio gravidanza e allattamento, alcune malattie muscolari, infezioni acute nella zona da trattare e intolleranze note. Se il trattamento è adatto a Lei, lo chiariamo in un colloquio prima di ogni trattamento.",
  ctaHA: "Il Suo appuntamento.",
  ctaHB: "Con la massima flessibilità.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Note legali",
  privacy: "Privacy",
};

const tr: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Berlin’de tıbbi kırışıklık tedavisi",
  metaDesc: "PALO SKIN by Dr. Vogel, Berlin Prenzlauer Berg: Dr. med. Sebastian Vogel tarafından tıbbi kırışıklık tedavisi. İş öncesi, iş sonrası ve hafta sonu randevu.",
  rateLong: "★ 5,0 danışan değerlendirmesi",
  rateShort: "★ 5,0",
  rateAria: "Google Maps’te 5,0 danışan değerlendirmesi",
  navAria: "Ana menü",
  navStudio: "Stüdyo",
  navTreat: "Tedaviler",
  navHow: "Süreç",
  navFaq: "Sorular",
  book: "Randevu al",
  menu: "Menü",
  heroEyebrow: "Berlin Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Tıbbi kırışıklık tedavisi ve Skin Booster. Kollwitzkiez’in tam ortasında.",
  googleA: "5,0",
  googleB: "Google’da",
  heroAlt: "Beyaz tişörtlü Dr. med. Sebastian Vogel, Berlin Prenzlauer Berg’deki PALO SKIN stüdyosunda masada",
  docRole: "Hekim ve PALO SKIN’in kurucusu",
  docHA: "Sakin bir",
  docHB: "el.",
  handAlt: "Dr. med. Sebastian Vogel’in, Berlin Prenzlauer Berg’deki PALO SKIN stüdyosunda siyah masanın üzerinde sakince üst üste duran elleri",
  quote: "“Ben Dr. med. Sebastian Vogel. Birkaç yıl cerrahide ve başka uzmanlık alanlarında çalıştım, binlerce estetik uygulama yaptım. PALO SKIN’de sizi bizzat ben tedavi ediyorum. Amacım, yüzünüze yakışan ölçülü sonuçlar.”",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Yol tarifi",
  studioOpen: "Stüdyoya göz atın",
  studioClose: "Fotoğrafları kapat",
  photoConsult: "Berlin Prenzlauer Berg’deki PALO SKIN stüdyosunda danışma alanı: siyah masa, üç açık renk koltuk ve mavi duvar objesi",
  photoTreat: "Berlin Prenzlauer Berg’deki PALO SKIN stüdyosunda tedavi koltuğu ve ahşap çıtalarla tedavi odası",
  photoStudio: "Berlin Prenzlauer Berg’deki PALO SKIN stüdyosunda ahşap çıtalar ve mavi duvar objesi",
  photoEntrance: "Berlin Prenzlauer Berg’de, Hagenauer Straße’deki PALO SKIN stüdyosunun girişindeki tabela",
  whyHA: "PALO SKIN’i kimler için",
  whyHB: "kurdum.",
  why1H: "Bekleme salonu yerine dakiklik.",
  why1P: "Randevusunu yoğun bir gündelik hayata sığdırmak zorunda olan herkes için.",
  why2H: "Neredeyse hiç evrak yok.",
  why2P: "Sadeliği sevenler için: Yalnızca önemli olanı soruyoruz.",
  why3H: "Steril değil, samimi.",
  why3P: "Doktordayken de kendini rahat hissetmek isteyenler için.",
  why4H: "Anladığınız bir dilde tedavi.",
  why4P: "Berlin ve dünya için: Almanca, İngilizce, İspanyolca, Fransızca ve Portekizce tedavi.",
  why5H: "Özellikle ince iğneler.",
  why5P: "Olabildiğince nazik bir tedavi isteyen herkes için.",
  why6H: "Yalnızca orijinal ürünler.",
  why6P: "Ne aldığını bilmek isteyenler için: Alman eczanelerinden.",
  treatHA: "Tam ihtiyacınız olan.",
  treatHB: "Adil fiyatlarla.",
  t1H: "Kırışıklık tedavisi ve dahası",
  t1D: "Kaş arası çizgileri, alın, kaz ayakları ve diğer bölgeler.",
  t1Alt: "Krem renginde ipek kıvrımı, Berlin Prenzlauer Berg’deki PALO SKIN’de kırışıklık tedavisi için görsel",
  t2H: "Çiğneme kası (masseter)",
  t2D: "Yüz hattı ve diş gıcırdatma.",
  t2Alt: "Gözleri kapalı, eli yanağında bir adam, Berlin Prenzlauer Berg’deki PALO SKIN’de çiğneme kası tedavisi için görsel",
  t3H: "Nefertiti lifting",
  t3D: "Boyun ve çene hattı.",
  t3Alt: "Nefertiti’nin profilden açık renk taş büstü, Berlin Prenzlauer Berg’deki PALO SKIN’de Nefertiti lifting için görsel",
  t4H: "Somon DNA’sı",
  t4D: "Göz altı morlukları ve göz çevresi için polinükleotidler.",
  t4Alt: "Bir kadının göz çevresi, Berlin Prenzlauer Berg’deki PALO SKIN’de somon DNA’sı tedavisi için görsel",
  priceFrom: (p) => `${p} ve\u00A0üzeri`,
  allPrices: "Tüm fiyatları görün",
  pZones: "Kırışıklık tedavisi ve dahası",
  pZone1: "1 bölge",
  pZone2: "2 bölge",
  pZone3: "3 bölge",
  pZoneMore: "her ek bölge",
  pNefD: "Boyun ve çene hattı",
  pAchselH: "Aşırı terleme (hiperhidroz)",
  pAchselD: "Koltuk altı",
  pLachsH: "Somon DNA’sı (polinükleotidler)",
  pLachs1: "Tek seans",
  pLachs4: "Dört seans",
  pnote: "* Yaklaşık fiyatlar. Ücretlendirme, Alman hekim ücret tarifesine (Gebührenordnung für Ärzte) göre yapılır. Fiyatlara katma değer vergisi dahildir.",
  howHA: "Önce görüşme.",
  howHB: "Sonra tedavi.",
  s1H: "Size ne zaman uygunsa.",
  s1P: "İş öncesi ve sonrası, hafta sonları da randevu. Randevunuzu 24 saat öncesine kadar kendiniz değiştirebilirsiniz.",
  s2H: "Ayrıntılı bir danışma.",
  s2P: "Neyi değiştirmek istersiniz? Olanakları, sınırları, riskleri ve maliyetleri konuşuruz.",
  s3H: "Hiçbir baskı olmadan.",
  s3P: "Tedavi size uygunsa aynı randevuda hemen yapılabilir. Biraz daha düşünmek isterseniz, sizi de aynı şekilde memnuniyetle karşılıyoruz.",
  revHA: "Danışanlarımız",
  revHB: "hakkımızda ne diyor.",
  allReviews: "Google Maps’teki tüm değerlendirmeler",
  faqHA: "Sık sorulan",
  faqHB: "sorular.",
  q1: "Bölge nedir?",
  a1: "Bir tedavi alanı, örneğin kaş arası çizgileri, alın veya kaz ayakları (iki taraf birlikte). Diğer bölgeler: Lip Flip, Brow Lift, dudak kenarları, portakal kabuğu çene, Gummy Smile, üst dudak çizgileri, Bunny Lines, burun inceltme.",
  q2: "İşe ne zaman dönebilirim?",
  a2: "Hemen ardından. Enjeksiyon noktalarındaki küçük kızarıklıklar genellikle birkaç dakika içinde kaybolur. Sonrasında nelere dikkat etmeniz gerektiğini önceden konuşuruz.",
  q3: "Kırışıklık tedavisinin etkisi ne zaman başlar ve ne kadar sürer?",
  a3: "Etki çoğunlukla iki ila üç gün sonra başlar ve yaklaşık iki hafta sonra tam olarak ortaya çıkar. Genellikle üç ila altı ay sürer, bu kişiden kişiye değişir.",
  q4: "Tedavi yapılmaması için nedenler var mı?",
  a4: "Evet, örneğin hamilelik ve emzirme dönemi, belirli kas rahatsızlıkları, tedavi bölgesindeki akut enfeksiyonlar ve bilinen aşırı duyarlılıklar. Tedavinin size uygun olup olmadığını her tedaviden önce görüşmede netleştiriyoruz.",
  ctaHA: "Randevunuz.",
  ctaHB: "Tamamen esnek.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Yasal bildirim",
  privacy: "Gizlilik",
};

const uk: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Лікарська корекція зморшок у Берліні",
  metaDesc: "PALO SKIN by Dr. Vogel у Берліні, Prenzlauer Berg: лікарська корекція зморшок від Dr. med. Sebastian Vogel. Прийом до та після роботи, а також у вихідні.",
  rateLong: "★ 5,0 відгуки клієнтів",
  rateShort: "★ 5,0",
  rateAria: "Оцінка 5,0 у відгуках клієнтів на Google Maps",
  navAria: "Головне меню",
  navStudio: "Студія",
  navTreat: "Процедури",
  navHow: "Як це відбувається",
  navFaq: "Питання",
  book: "Записатися",
  menu: "Меню",
  heroEyebrow: "Берлін, Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Лікарська корекція зморшок і Skin Booster. У самому серці Kollwitzkiez.",
  googleA: "5,0",
  googleB: "на Google",
  heroAlt: "Dr. med. Sebastian Vogel у білій футболці за столом у студії PALO SKIN у Берліні, Prenzlauer Berg",
  docRole: "Лікар і засновник PALO SKIN",
  docHA: "Спокійна",
  docHB: "рука.",
  handAlt: "Спокійно складені руки Dr. med. Sebastian Vogel на чорному столі в студії PALO SKIN у Берліні, Prenzlauer Berg",
  quote: "«Я Dr. med. Sebastian Vogel. Кілька років я працював у хірургії та інших галузях медицини і провів багато тисяч естетичних процедур. У PALO SKIN процедури Вам проводжу я сам. Моя мета: делікатні результати, які пасують саме Вашому обличчю.»",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Як нас знайти",
  studioOpen: "Переглянути студію",
  studioClose: "Закрити фото",
  photoConsult: "Зона консультацій у студії PALO SKIN у Берліні, Prenzlauer Berg: чорний стіл, три світлі крісла і синій настінний об’єкт",
  photoTreat: "Кімната для процедур у студії PALO SKIN у Берліні, Prenzlauer Berg, з кріслом для процедур і дерев’яними рейками",
  photoStudio: "Дерев’яні рейки і синій настінний об’єкт у студії PALO SKIN у Берліні, Prenzlauer Berg",
  photoEntrance: "Табличка біля входу до студії PALO SKIN на Hagenauer Straße у Берліні, Prenzlauer Berg",
  whyHA: "Для кого я заснував",
  whyHB: "PALO SKIN.",
  why1H: "Вчасно, а не в черзі.",
  why1P: "Для всіх, кому треба вписати візит у насичені будні.",
  why2H: "Мінімум паперів.",
  why2P: "Для тих, хто любить простоту: ми питаємо лише про головне.",
  why3H: "Затишно, а не по-лікарняному.",
  why3P: "Для тих, хто хоче почуватися комфортно й у лікаря.",
  why4H: "Процедура зрозумілою Вам мовою.",
  why4P: "Для Берліна і всього світу: процедури німецькою, англійською, іспанською, французькою та португальською мовами.",
  why5H: "Особливо тонкі голки.",
  why5P: "Для всіх, хто бажає якомога делікатнішої процедури.",
  why6H: "Лише оригінальні препарати.",
  why6P: "Для тих, хто хоче знати, що отримує: препарати з німецьких аптек.",
  treatHA: "Саме те, що Вам потрібно.",
  treatHB: "За чесними цінами.",
  t1H: "Корекція зморшок і не тільки",
  t1D: "Міжбрівна зморшка, чоло, «гусячі лапки» та інші зони.",
  t1Alt: "Складка шовку кремового кольору, зображення до корекції зморшок у PALO SKIN у Берліні, Prenzlauer Berg",
  t2H: "Жувальний м’яз (масетер)",
  t2D: "Контур обличчя та скрегіт зубами.",
  t2Alt: "Чоловік із заплющеними очима, рука на щоці, зображення до процедури для жувального м’яза в PALO SKIN у Берліні, Prenzlauer Berg",
  t3H: "Ліфтинг Nefertiti",
  t3D: "Шия та контур нижньої щелепи.",
  t3Alt: "Світле кам’яне погруддя Нефертіті в профіль, зображення до ліфтингу Nefertiti в PALO SKIN у Берліні, Prenzlauer Berg",
  t4H: "ДНК лосося",
  t4D: "Полінуклеотиди при темних колах під очима та для зони навколо очей.",
  t4Alt: "Ділянка навколо очей жінки, зображення до процедури з ДНК лосося в PALO SKIN у Берліні, Prenzlauer Berg",
  priceFrom: (p) => `від ${p}`,
  allPrices: "Переглянути всі ціни",
  pZones: "Корекція зморшок і не тільки",
  pZone1: "1 зона",
  pZone2: "2 зони",
  pZone3: "3 зони",
  pZoneMore: "кожна наступна зона",
  pNefD: "Шия та контур нижньої щелепи",
  pAchselH: "Надмірне потовиділення (гіпергідроз)",
  pAchselD: "Пахви",
  pLachsH: "ДНК лосося (полінуклеотиди)",
  pLachs1: "Одна процедура",
  pLachs4: "Чотири процедури",
  pnote: "* Орієнтовні ціни. Розрахунок згідно з німецьким тарифом на лікарські послуги (Gebührenordnung für Ärzte). Ціни включають податок на додану вартість.",
  howHA: "Спершу розмова.",
  howHB: "Потім процедура.",
  s1H: "Коли Вам зручно.",
  s1P: "Час до і після роботи, а також у вихідні. Перенести запис Ви можете самостійно, не пізніше ніж за 24 години.",
  s2H: "Детальна консультація.",
  s2P: "Що Ви хотіли б змінити? Ми обговорюємо можливості, межі, ризики та вартість.",
  s3H: "Без жодного тиску.",
  s3P: "Якщо процедура Вам підходить, її можна провести одразу під час того самого візиту. А якщо Ви хочете ще подумати, ми раді Вам так само.",
  revHA: "Що клієнти",
  revHB: "кажуть про нас.",
  allReviews: "Усі відгуки на Google Maps",
  faqHA: "Часті",
  faqHB: "запитання.",
  q1: "Що таке зона?",
  a1: "Ділянка, яку обробляють під час процедури, наприклад міжбрівна зморшка, чоло або «гусячі лапки» (обидві сторони разом). Інші зони: Lip Flip, Brow Lift, куточки рота, підборіддя «апельсинова кірка», Gummy Smile, зморшки над верхньою губою, Bunny Lines, звуження носа.",
  q2: "Коли я зможу повернутися до роботи?",
  a2: "Одразу після процедури. Невелике почервоніння в місцях уколів зазвичай зникає за кілька хвилин. Що варто врахувати після процедури, ми обговоримо з Вами заздалегідь.",
  q3: "Коли з’являється ефект корекції зморшок і як довго він тримається?",
  a3: "Ефект зазвичай з’являється через два-три дні, а повністю проявляється приблизно через два тижні. Як правило, він тримається від трьох до шести місяців, у кожної людини по-різному.",
  q4: "Чи є причини не проводити процедуру?",
  a4: "Так, наприклад вагітність і грудне вигодовування, певні захворювання м’язів, гострі інфекції в зоні процедури та відома непереносимість. Чи підходить процедура саме Вам, ми з’ясовуємо в розмові перед кожною процедурою.",
  ctaHA: "Ваш візит.",
  ctaHB: "Як Вам зручно.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Вихідні дані",
  privacy: "Захист даних",
};

const ar: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | علاج طبي للتجاعيد في برلين",
  metaDesc: "PALO SKIN by Dr. Vogel في Prenzlauer Berg ببرلين: علاج طبي للتجاعيد على يد Dr. med. Sebastian Vogel. مواعيد قبل العمل وبعده وفي عطلة نهاية الأسبوع.",
  rateLong: "★ 5.0 في تقييمات العملاء",
  rateShort: "★ 5.0",
  rateAria: "5.0 في تقييمات العملاء على Google Maps",
  navAria: "القائمة الرئيسية",
  navStudio: "المركز",
  navTreat: "العلاجات",
  navHow: "سير الزيارة",
  navFaq: "أسئلة",
  book: "حجز موعد",
  menu: "القائمة",
  heroEyebrow: "Prenzlauer Berg، برلين",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "علاج طبي للتجاعيد وسكين بوستر. في قلب Kollwitzkiez.",
  googleA: "5.0",
  googleB: "على Google",
  heroAlt: "Dr. med. Sebastian Vogel بقميص أبيض جالسًا إلى الطاولة في مركز PALO SKIN في Prenzlauer Berg ببرلين",
  docRole: "طبيب ومؤسس PALO SKIN",
  docHA: "يد",
  docHB: "ثابتة.",
  handAlt: "يدا Dr. med. Sebastian Vogel موضوعتان بهدوء إحداهما فوق الأخرى على الطاولة السوداء في مركز PALO SKIN في Prenzlauer Berg ببرلين",
  quote: "«أنا Dr. med. Sebastian Vogel. عملتُ عدة سنوات في الجراحة وفي تخصصات طبية أخرى، وأجريتُ آلاف العلاجات التجميلية. في PALO SKIN أعالجكم بنفسي. هدفي نتائج طبيعية غير مبالغ فيها، تنسجم مع ملامح وجهكم.»",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "الطريق إلينا",
  studioOpen: "إلقاء نظرة على المركز",
  studioClose: "إغلاق الصور",
  photoConsult: "منطقة الاستشارة في مركز PALO SKIN في Prenzlauer Berg ببرلين: طاولة سوداء وثلاثة مقاعد فاتحة وعمل فني أزرق على الجدار",
  photoTreat: "غرفة العلاج في مركز PALO SKIN في Prenzlauer Berg ببرلين، مع كرسي العلاج وألواح خشبية",
  photoStudio: "ألواح خشبية وعمل فني أزرق على الجدار في مركز PALO SKIN في Prenzlauer Berg ببرلين",
  photoEntrance: "اللافتة عند مدخل مركز PALO SKIN في شارع Hagenauer Straße في Prenzlauer Berg ببرلين",
  whyHA: "لمن أسّستُ",
  whyHB: "PALO SKIN.",
  why1H: "في الموعد بدل غرفة الانتظار.",
  why1P: "لكل من يحتاج إلى إيجاد مكان لموعده في يوم مزدحم.",
  why2H: "أوراق قليلة جدًا.",
  why2P: "لمن يحب البساطة: لا نسأل إلا عمّا يهم.",
  why3H: "أجواء مريحة بدل الطابع السريري.",
  why3P: "لمن يرغب في الشعور بالراحة حتى عند الطبيب.",
  why4H: "العلاج بلغتكم.",
  why4P: "لبرلين وللعالم: العلاج بالألمانية والإنجليزية والإسبانية والفرنسية والبرتغالية.",
  why5H: "إبر رفيعة للغاية.",
  why5P: "لكل من يرغب في علاج لطيف قدر الإمكان.",
  why6H: "مستحضرات أصلية فقط.",
  why6P: "لمن يريد أن يعرف ما يحصل عليه: من صيدليات ألمانية.",
  treatHA: "ما تحتاجونه بالضبط.",
  treatHB: "بأسعار عادلة.",
  t1H: "علاج التجاعيد والمزيد",
  t1D: "خطوط ما بين الحاجبين، والجبهة، وتجاعيد زوايا العينين، ومناطق أخرى.",
  t1Alt: "طيّة حرير بلون كريمي، صورة لعلاج التجاعيد في PALO SKIN في Prenzlauer Berg ببرلين",
  t2H: "عضلة المضغ (الماضغة)",
  t2D: "محيط الوجه وصرير الأسنان.",
  t2Alt: "رجل مغمض العينين، يده على خده، صورة لعلاج عضلة المضغ في PALO SKIN في Prenzlauer Berg ببرلين",
  t3H: "شد نفرتيتي",
  t3D: "الرقبة وخط الفك.",
  t3Alt: "تمثال نصفي حجري فاتح لنفرتيتي من الجانب، صورة لشد نفرتيتي في PALO SKIN في Prenzlauer Berg ببرلين",
  t4H: "الحمض النووي للسلمون",
  t4D: "بولي نيوكليوتيدات للهالات السوداء ومنطقة حول العينين.",
  t4Alt: "منطقة العينين لدى امرأة، صورة لعلاج الحمض النووي للسلمون في PALO SKIN في Prenzlauer Berg ببرلين",
  priceFrom: (p) => `ابتداءً من ${p}`,
  allPrices: "الاطلاع على جميع الأسعار",
  pZones: "علاج التجاعيد والمزيد",
  pZone1: "منطقة واحدة",
  pZone2: "منطقتان",
  pZone3: "3 مناطق",
  pZoneMore: "كل منطقة إضافية",
  pNefD: "الرقبة وخط الفك",
  pAchselH: "التعرق المفرط (فرط التعرق)",
  pAchselD: "منطقة الإبطين",
  pLachsH: "الحمض النووي للسلمون (بولي نيوكليوتيدات)",
  pLachs1: "جلسة واحدة",
  pLachs4: "أربع جلسات",
  pnote: "* أسعار استرشادية. تتم المحاسبة وفق لائحة أتعاب الأطباء الألمانية (Gebührenordnung für Ärzte). الأسعار شاملة ضريبة القيمة المضافة.",
  howHA: "أولًا نتحدث معًا.",
  howHB: "ثم العلاج.",
  s1H: "في الوقت الذي يناسبكم.",
  s1P: "مواعيد قبل العمل وبعده، وفي عطلة نهاية الأسبوع أيضًا. ويمكنكم تغيير الموعد بأنفسكم حتى 24 ساعة قبله.",
  s2H: "استشارة مفصّلة.",
  s2P: "ما الذي ترغبون في تغييره؟ نناقش معًا الإمكانيات والحدود والمخاطر والتكاليف.",
  s3H: "دون أي ضغط.",
  s3P: "إذا كان العلاج مناسبًا لكم، يمكن إجراؤه مباشرة في الموعد نفسه. وإذا فضّلتم التفكير مرة أخرى، فأنتم مرحَّب بكم بالقدر نفسه.",
  revHA: "ما يقوله عملاؤنا",
  revHB: "عنّا.",
  allReviews: "جميع التقييمات على Google Maps",
  faqHA: "أسئلة",
  faqHB: "شائعة.",
  q1: "ما المقصود بالمنطقة؟",
  a1: "منطقة علاج واحدة، مثل خطوط ما بين الحاجبين أو الجبهة أو تجاعيد زوايا العينين (الجانبان معًا). ومن المناطق الأخرى: ليب فليب، ورفع الحاجبين، وزوايا الفم، وتجعّد الذقن، والابتسامة اللثوية، وتجاعيد الشفة العليا، وتجاعيد جانبي الأنف، وتنحيف الأنف.",
  q2: "متى يمكنني العودة إلى العمل؟",
  a2: "مباشرة بعد العلاج. يختفي الاحمرار الخفيف في مواضع الحقن عادةً خلال دقائق قليلة. ونناقش معكم مسبقًا ما ينبغي مراعاته بعد العلاج.",
  q3: "متى يبدأ مفعول علاج التجاعيد، وكم يدوم؟",
  a3: "يبدأ المفعول عادةً بعد يومين إلى ثلاثة أيام، ويكتمل بعد نحو أسبوعين. ويستمر في الغالب من ثلاثة إلى ستة أشهر، ويختلف ذلك من شخص لآخر.",
  q4: "هل توجد أسباب تمنع العلاج؟",
  a4: "نعم، مثل الحمل والرضاعة، وبعض أمراض العضلات، والالتهابات الحادة في منطقة العلاج، وحالات عدم التحمل المعروفة. ونوضح معكم في الحديث قبل كل علاج ما إذا كان العلاج مناسبًا لكم.",
  ctaHA: "موعدكم.",
  ctaHB: "بكل مرونة.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "الإشعار القانوني",
  privacy: "حماية البيانات",
};

export const HOME_TEXTS: Record<Lang, HomeTexts> = { de, en, es, fr, pt, it, tr, uk, ar };


/* Französisch: schmales geschütztes Leerzeichen vor ? ! : ; und innerhalb der Anführungszeichen (wie in lib/texts.ts) */
{
  const fr = HOME_TEXTS.fr as unknown as Record<string, unknown>;
  for (const k of Object.keys(fr)) {
    const v = fr[k];
    if (typeof v === "string") fr[k] = v.replace(/ ([?!:;»])/g, " $1").replace(/« /g, "« ");
  }
}
