/*
 * Texte der Startseite, Entwurf B „Persönlich“ (Vorlage vom 5. Oktober 2026). Deutsch wörtlich aus der Vorlage,
 * von Dr. Vogel einzeln freigegeben; die anderen Sprachen sind daraus übersetzt (Ukrainisch und Arabisch:
 * Muttersprachler-Prüfung offen). Kopfzeile und Fußzeile nutzen dieselben Texte auch auf der Buchungsseite.
 * title und metaDesc bleiben wie bisher (Seitentitel und Linkvorschau unverändert, lib/share-meta.ts).
 * Zwei Teile einer Überschrift: …A normal, …B kursiv in Blau (Newsreader).
 */
import type { Lang } from "./i18n";

export interface HomeTexts {
  title: string;
  metaDesc: string;
  /* Kopfzeile */
  rateLong: string;
  rateShort: string;
  rateAria: string;
  navAria: string;
  navStudio: string;
  navTreat: string;
  navHow: string;
  navFaq: string;
  book: string;
  menu: string;
  /* Start */
  heroEyebrow: string;
  h1A: string;
  h1B: string;
  lead: string;
  googleA: string;
  googleB: string;
  heroAlt: string;
  docRole: string;
  /* Ihr Arzt */
  docEyebrow: string;
  docHA: string;
  docHB: string;
  handAlt: string;
  quote: string;
  address: string;
  mapL: string;
  studioOpen: string;
  studioClose: string;
  photoConsult: string;
  photoTreat: string;
  photoStudio: string;
  photoEntrance: string;
  /* Für wen */
  whyEyebrow: string;
  whyHA: string;
  whyHB: string;
  why1H: string;
  why1P: string;
  why2H: string;
  why2P: string;
  why3H: string;
  why3P: string;
  why4H: string;
  why4P: string;
  why5H: string;
  why5P: string;
  why6H: string;
  why6P: string;
  /* Behandlungen */
  treatEyebrow: string;
  treatHA: string;
  treatHB: string;
  t1H: string;
  t1D: string;
  t1Alt: string;
  t2H: string;
  t2D: string;
  t2Alt: string;
  t3H: string;
  t3D: string;
  t3Alt: string;
  t4H: string;
  t4D: string;
  t4Alt: string;
  /** „ab 120 €*“ */
  priceFrom: (price: string) => string;
  allPrices: string;
  pZones: string;
  pZone1: string;
  pZone2: string;
  pZone3: string;
  pZoneMore: string;
  pNefD: string;
  pAchselH: string;
  pAchselD: string;
  pLachsH: string;
  pLachs1: string;
  pLachs4: string;
  pnote: string;
  /* Ablauf */
  howEyebrow: string;
  howHA: string;
  howHB: string;
  s1H: string;
  s1P: string;
  s2H: string;
  s2P: string;
  s3H: string;
  s3P: string;
  /* Bewertungen */
  revEyebrow: string;
  revHA: string;
  revHB: string;
  allReviews: string;
  /* Fragen */
  faqHA: string;
  faqHB: string;
  q1: string;
  a1: string;
  q2: string;
  a2: string;
  q3: string;
  a3: string;
  q4: string;
  a4: string;
  /* Abschluss und Fußzeile */
  ctaHA: string;
  ctaHB: string;
  copyright: string;
  imprint: string;
  privacy: string;
}

/* Kundenstimmen von Google Maps: Zitate bleiben in der Originalsprache und werden nicht übersetzt */
export const REVIEWS: { text: string; lang: Lang; name: string; initial: string }[] = [
  { text: "„Ich bin selbst Ärztin (…). Bei Dr. Sebastian Vogel habe ich mich von Anfang an sehr gut aufgehoben gefühlt.“", lang: "de", name: "Kathleen", initial: "K" },
  { text: "„Er nimmt sich immer Zeit und hat beim ersten Mal direkt gesehen, dass meine linke Zornesfalte stärker ist als die rechte (…).“", lang: "de", name: "Antje D.", initial: "A" },
  { text: "„Dr. Vogel is a true professional (…). The location is also beautifully designed and makes you feel welcomed immediately.“", lang: "en", name: "Cyril S.", initial: "C" },
];

const de: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Ärztliche Faltenbehandlung in Berlin",
  metaDesc: "PALO SKIN by Dr. Vogel in Berlin Prenzlauer Berg: ärztliche Faltenbehandlung durch Dr. med. Sebastian Vogel. Termine vor und nach der Arbeit und am Wochenende.",
  rateLong: "★ 5,0 Kundenbewertungen",
  rateShort: "★ 5,0",
  rateAria: "5,0 Kundenbewertungen auf Google Maps",
  navAria: "Hauptmenü",
  navStudio: "Studio",
  navTreat: "Behandlungen",
  navHow: "Ablauf",
  navFaq: "Fragen",
  book: "Termin buchen",
  menu: "Menü",
  heroEyebrow: "Berlin Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Ärztliche Faltenbehandlung und Skin Booster. Mitten im Kollwitzkiez.",
  googleA: "5,0",
  googleB: "bei Google",
  heroAlt: "Dr. med. Sebastian Vogel im Studio PALO SKIN",
  docRole: "Arzt und Gründer von PALO SKIN",
  docEyebrow: "Ihr Arzt · chirurgisch geschult",
  docHA: "Eine ruhige",
  docHB: "Hand.",
  handAlt: "Ruhig übereinanderliegende Hände von Dr. Vogel auf dem schwarzen Tisch im Studio",
  quote: "„Ich bin Dr. med. Sebastian Vogel. Ich habe mehrere Jahre in der Chirurgie und in weiteren Fachrichtungen gearbeitet und viele tausend ästhetische Behandlungen durchgeführt. Bei PALO SKIN behandle ich Sie selbst. Mein Ziel sind dezente Ergebnisse, die zu Ihrem Gesicht passen.“",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "So finden Sie uns",
  studioOpen: "Das Studio ansehen",
  studioClose: "Fotos schließen",
  photoConsult: "Beratungsraum",
  photoTreat: "Behandlungsraum",
  photoStudio: "Im Studio",
  photoEntrance: "Eingang",
  whyEyebrow: "Für wen",
  whyHA: "Für wen ich PALO SKIN",
  whyHB: "gegründet habe.",
  why1H: "Pünktlich statt Wartezimmer.",
  why1P: "Für alle, die ihren Termin in einen vollen Alltag einbauen müssen.",
  why2H: "Kaum Papierkram.",
  why2P: "Für Menschen, die es einfach mögen: Wir fragen nur, was zählt.",
  why3H: "Gemütlich statt klinisch.",
  why3P: "Für diejenigen, die sich auch beim Arzt wohlfühlen möchten.",
  why4H: "Behandlung in Ihrer Sprache.",
  why4P: "Für Berlin und die Welt: Behandlung auf Deutsch, Englisch, Spanisch, Französisch und Portugiesisch.",
  why5H: "Besonders feine Nadeln.",
  why5P: "Für alle, die eine möglichst sanfte Behandlung möchten.",
  why6H: "Nur Originalpräparate.",
  why6P: "Für Menschen, die wissen wollen, was sie bekommen: aus deutschen Apotheken.",
  treatEyebrow: "Behandlungen und Preise",
  treatHA: "Genau, was Sie brauchen.",
  treatHB: "Zu fairen Preisen.",
  t1H: "Faltenbehandlung und mehr",
  t1D: "Zornesfalte, Stirn, Krähenfüße und weitere Zonen.",
  t1Alt: "Seidenfalte in Creme",
  t2H: "Kaumuskel (Masseter)",
  t2D: "Gesichtskontur und Zähneknirschen.",
  t2Alt: "Mann mit geschlossenen Augen, Hand an der Wange",
  t3H: "Nefertiti-Lift",
  t3D: "Hals und Kieferkontur.",
  t3Alt: "helle Steinbüste der Nofretete im Profil",
  t4H: "Lachs-DNA",
  t4D: "Polynukleotide für dunkle Augenringe und die Augenpartie.",
  t4Alt: "Augenpartie einer Frau",
  priceFrom: (p) => `ab ${p}`,
  allPrices: "Alle Preise ansehen",
  pZones: "Faltenbehandlung und mehr",
  pZone1: "1 Zone",
  pZone2: "2 Zonen",
  pZone3: "3 Zonen",
  pZoneMore: "jede weitere Zone",
  pNefD: "Hals und Kieferkontur",
  pAchselH: "Übermäßiges Schwitzen (Hyperhidrose)",
  pAchselD: "Achseln",
  pLachsH: "Lachs-DNA (Polynukleotide)",
  pLachs1: "Eine Behandlung",
  pLachs4: "Vier Behandlungen",
  pnote: "* Richtwerte. Abrechnung nach der Gebührenordnung für Ärzte. Preise inklusive Mehrwertsteuer.",
  howEyebrow: "Ihr Termin",
  howHA: "Erst das Gespräch.",
  howHB: "Dann die Behandlung.",
  s1H: "Wann es Ihnen passt.",
  s1P: "Termine vor und nach der Arbeit und auch am Wochenende. Verschieben können Sie selbst, bis 24 Stunden vorher.",
  s2H: "Eine ausführliche Beratung.",
  s2P: "Was möchten Sie verändern? Wir besprechen Möglichkeiten, Grenzen, Risiken und Kosten.",
  s3H: "Ganz ohne Druck.",
  s3P: "Passt die Behandlung zu Ihnen, ist sie direkt im selben Termin möglich. Und wer lieber noch einmal nachdenkt, ist genauso willkommen.",
  revEyebrow: "Bewertungen",
  revHA: "Was Kunden",
  revHB: "über uns sagen.",
  allReviews: "Alle Bewertungen auf Google Maps",
  faqHA: "Häufige",
  faqHB: "Fragen.",
  q1: "Was ist eine Zone?",
  a1: "Ein Behandlungsbereich, zum Beispiel Zornesfalte, Stirn oder Krähenfüße (beide Seiten zusammen). Weitere Zonen: Lip Flip, Brow Lift, Mundwinkel, Erdbeerkinn, Gummy Smile, Oberlippenfältchen, Bunny Lines, Nasenverschmälerung.",
  q2: "Wann kann ich wieder zur Arbeit?",
  a2: "Direkt danach. Kleine Rötungen an den Einstichstellen verschwinden in der Regel nach wenigen Minuten. Was Sie danach beachten sollten, besprechen wir vorab.",
  q3: "Wann wirkt die Faltenbehandlung und wie lange hält sie?",
  a3: "Die Wirkung beginnt meist nach zwei bis drei Tagen und ist nach etwa zwei Wochen vollständig. Sie hält in der Regel drei bis sechs Monate, das ist von Mensch zu Mensch verschieden.",
  q4: "Gibt es Gründe, nicht zu behandeln?",
  a4: "Ja, zum Beispiel Schwangerschaft und Stillzeit, bestimmte Muskelerkrankungen, akute Infekte im Behandlungsbereich und bekannte Unverträglichkeiten. Ob die Behandlung für Sie geeignet ist, klären wir vor jeder Behandlung im Gespräch.",
  ctaHA: "Ihr Termin.",
  ctaHB: "Ganz flexibel.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Impressum",
  privacy: "Datenschutz",
};

/* Übersetzungen aus der deutschen Fassung (5. Oktober 2026). Ukrainisch und Arabisch: Muttersprachler-Prüfung offen. */
const en: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Physician-led wrinkle treatment in Berlin",
  metaDesc: "PALO SKIN by Dr. Vogel in Berlin Prenzlauer Berg: physician-led wrinkle treatment by Dr. med. Sebastian Vogel. Open before and after work and at weekends.",
  rateLong: "★ 5.0 client rating",
  rateShort: "★ 5.0",
  rateAria: "5.0 client rating on Google Maps",
  navAria: "Main menu",
  navStudio: "Studio",
  navTreat: "Treatments",
  navHow: "How it works",
  navFaq: "Questions",
  book: "Book appointment",
  menu: "Menu",
  heroEyebrow: "Berlin Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Physician-led wrinkle treatment and Skin Booster. Right in the Kollwitzkiez.",
  googleA: "5.0",
  googleB: "on Google",
  heroAlt: "Dr. med. Sebastian Vogel in the PALO SKIN studio",
  docRole: "Physician and founder of PALO SKIN",
  docEyebrow: "Your physician · trained in surgery",
  docHA: "A steady",
  docHB: "hand.",
  handAlt: "Dr. Vogel’s hands resting calmly on top of each other on the black table in the studio",
  quote: "“I am Dr. med. Sebastian Vogel. I worked for several years in surgery and other specialities, and I have performed many thousands of aesthetic treatments. At PALO SKIN, I treat you myself. My aim is subtle results that suit your face.”",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "How to find us",
  studioOpen: "See the studio",
  studioClose: "Close photos",
  photoConsult: "Consultation room",
  photoTreat: "Treatment room",
  photoStudio: "In the studio",
  photoEntrance: "Entrance",
  whyEyebrow: "Who it is for",
  whyHA: "Who I founded PALO SKIN",
  whyHB: "for.",
  why1H: "On time, no waiting room.",
  why1P: "For everyone who has to fit their appointment into a busy everyday life.",
  why2H: "Hardly any paperwork.",
  why2P: "For people who like things simple: we only ask what matters.",
  why3H: "Cosy, not clinical.",
  why3P: "For those who want to feel at ease, even at the doctor’s.",
  why4H: "Treatment in your language.",
  why4P: "For Berlin and the world: treatment in German, English, Spanish, French and Portuguese.",
  why5H: "Especially fine needles.",
  why5P: "For everyone who would like the gentlest possible treatment.",
  why6H: "Original products only.",
  why6P: "For people who want to know what they are getting: from German pharmacies.",
  treatEyebrow: "Treatments and prices",
  treatHA: "Exactly what you need.",
  treatHB: "At fair prices.",
  t1H: "Wrinkle treatment and more",
  t1D: "Frown lines, forehead, crow’s feet and other zones.",
  t1Alt: "Fold of cream-coloured silk",
  t2H: "Jaw muscle (masseter)",
  t2D: "Facial contour and teeth grinding.",
  t2Alt: "Man with his eyes closed, hand on his cheek",
  t3H: "Nefertiti lift",
  t3D: "Neck and jawline.",
  t3Alt: "Pale stone bust of Nefertiti in profile",
  t4H: "Salmon DNA",
  t4D: "Polynucleotides for dark circles and the eye area.",
  t4Alt: "A woman’s eye area",
  priceFrom: (p) => `from ${p}`,
  allPrices: "See all prices",
  pZones: "Wrinkle treatment and more",
  pZone1: "1 zone",
  pZone2: "2 zones",
  pZone3: "3 zones",
  pZoneMore: "each additional zone",
  pNefD: "Neck and jawline",
  pAchselH: "Excessive sweating (hyperhidrosis)",
  pAchselD: "Underarms",
  pLachsH: "Salmon DNA (polynucleotides)",
  pLachs1: "One treatment",
  pLachs4: "Four treatments",
  pnote: "* Guide prices. Billed according to the German fee schedule for physicians (Gebührenordnung für Ärzte). Prices include value added tax.",
  howEyebrow: "Your appointment",
  howHA: "First we talk.",
  howHB: "Then the treatment.",
  s1H: "Whenever suits you.",
  s1P: "Appointments before and after work, and at weekends too. You can reschedule yourself up to 24 hours in advance.",
  s2H: "A thorough consultation.",
  s2P: "What would you like to change? We discuss the options, limits, risks and costs.",
  s3H: "No pressure at all.",
  s3P: "If the treatment suits you, it can be done in the same appointment. And if you would rather think it over, you are just as welcome.",
  revEyebrow: "Reviews",
  revHA: "What clients",
  revHB: "say about us.",
  allReviews: "All reviews on Google Maps",
  faqHA: "Common",
  faqHB: "questions.",
  q1: "What is a zone?",
  a1: "A treatment area, for example the frown lines, forehead or crow’s feet (both sides together). Further zones: Lip Flip, Brow Lift, mouth corners, dimpled chin, Gummy Smile, upper lip lines, Bunny Lines, nose slimming.",
  q2: "When can I go back to work?",
  a2: "Straight away. Small red marks at the injection points usually disappear within a few minutes. We talk beforehand about what to bear in mind afterwards.",
  q3: "When does the wrinkle treatment take effect, and how long does it last?",
  a3: "The effect usually begins after two to three days and is complete after about two weeks. It generally lasts three to six months, which varies from person to person.",
  q4: "Are there reasons not to treat?",
  a4: "Yes, for example pregnancy and breastfeeding, certain muscle disorders, acute infections in the treatment area and known intolerances. Before every treatment, we talk through whether it is suitable for you.",
  ctaHA: "Your visit.",
  ctaHB: "Fully flexible.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Legal notice",
  privacy: "Privacy",
};

const es: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Tratamiento médico de arrugas en Berlín",
  metaDesc: "PALO SKIN by Dr. Vogel en Berlín Prenzlauer Berg: tratamiento médico de arrugas del Dr. med. Sebastian Vogel. Citas antes y tras el trabajo y el fin de semana.",
  rateLong: "★ 5,0 en valoraciones de clientes",
  rateShort: "★ 5,0",
  rateAria: "Valoración de clientes de 5,0 en Google Maps",
  navAria: "Menú principal",
  navStudio: "Estudio",
  navTreat: "Tratamientos",
  navHow: "Cómo funciona",
  navFaq: "Preguntas",
  book: "Reservar cita",
  menu: "Menú",
  heroEyebrow: "Berlín Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Tratamiento médico de arrugas y Skin Booster. En pleno Kollwitzkiez.",
  googleA: "5,0",
  googleB: "en Google",
  heroAlt: "El Dr. med. Sebastian Vogel en el estudio PALO SKIN",
  docRole: "Médico y fundador de PALO SKIN",
  docEyebrow: "Su médico · formación quirúrgica",
  docHA: "Una mano",
  docHB: "serena.",
  handAlt: "Las manos del Dr. Vogel, cruzadas con calma sobre la mesa negra del estudio",
  quote: "«Soy el Dr. med. Sebastian Vogel. He trabajado varios años en cirugía y en otras especialidades y he realizado miles de tratamientos estéticos. En PALO SKIN le trato yo personalmente. Mi objetivo son resultados discretos, acordes con su rostro.»",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Cómo llegar",
  studioOpen: "Ver el estudio",
  studioClose: "Cerrar las fotos",
  photoConsult: "Sala de asesoramiento",
  photoTreat: "Sala de tratamiento",
  photoStudio: "En el estudio",
  photoEntrance: "Entrada",
  whyEyebrow: "Para quién",
  whyHA: "Para quién he creado",
  whyHB: "PALO SKIN.",
  why1H: "Puntualidad, sin sala de espera.",
  why1P: "Para quienes tienen que encajar su cita en un día a día muy lleno.",
  why2H: "Apenas papeleo.",
  why2P: "Para quienes prefieren lo sencillo: solo preguntamos lo que importa.",
  why3H: "Acogedor, no clínico.",
  why3P: "Para quienes quieren sentirse a gusto también al ir al médico.",
  why4H: "Tratamiento en su idioma.",
  why4P: "Para Berlín y el mundo: tratamiento en alemán, inglés, español, francés y portugués.",
  why5H: "Agujas especialmente finas.",
  why5P: "Para quienes desean un tratamiento lo más suave posible.",
  why6H: "Solo preparados originales.",
  why6P: "Para quienes quieren saber qué reciben: de farmacias alemanas.",
  treatEyebrow: "Tratamientos y precios",
  treatHA: "Exactamente lo que necesita.",
  treatHB: "A precios justos.",
  t1H: "Tratamiento de arrugas y más",
  t1D: "Entrecejo, frente, patas de gallo y otras zonas.",
  t1Alt: "Pliegue de seda en color crema",
  t2H: "Masetero (músculo de la mandíbula)",
  t2D: "Contorno facial y bruxismo.",
  t2Alt: "Hombre con los ojos cerrados y la mano en la mejilla",
  t3H: "Lifting Nefertiti",
  t3D: "Cuello y contorno mandibular.",
  t3Alt: "Busto de piedra clara de Nefertiti de perfil",
  t4H: "ADN de salmón",
  t4D: "Polinucleótidos para las ojeras y el contorno de ojos.",
  t4Alt: "Contorno de ojos de una mujer",
  priceFrom: (p) => `desde ${p}`,
  allPrices: "Ver todos los precios",
  pZones: "Tratamiento de arrugas y más",
  pZone1: "1 zona",
  pZone2: "2 zonas",
  pZone3: "3 zonas",
  pZoneMore: "cada zona adicional",
  pNefD: "Cuello y contorno mandibular",
  pAchselH: "Sudoración excesiva (hiperhidrosis)",
  pAchselD: "Axilas",
  pLachsH: "ADN de salmón (polinucleótidos)",
  pLachs1: "Un tratamiento",
  pLachs4: "Cuatro tratamientos",
  pnote: "* Precios orientativos. Facturación según el baremo alemán de honorarios médicos (Gebührenordnung für Ärzte). Precios con el impuesto sobre el valor añadido incluido.",
  howEyebrow: "Su cita",
  howHA: "Primero hablamos.",
  howHB: "Después, el tratamiento.",
  s1H: "Cuando le venga bien.",
  s1P: "Citas antes y después del trabajo, y también los fines de semana. Puede cambiar la cita por su cuenta hasta 24 horas antes.",
  s2H: "Un asesoramiento detallado.",
  s2P: "¿Qué le gustaría cambiar? Hablamos de las posibilidades, los límites, los riesgos y los costes.",
  s3H: "Sin ninguna presión.",
  s3P: "Si el tratamiento es adecuado para usted, puede hacerse en la misma cita. Y quien prefiera pensarlo con calma es igual de bienvenido.",
  revEyebrow: "Opiniones",
  revHA: "Qué dicen",
  revHB: "nuestros clientes.",
  allReviews: "Todas las opiniones en Google Maps",
  faqHA: "Dudas",
  faqHB: "frecuentes.",
  q1: "¿Qué es una zona?",
  a1: "Una zona de tratamiento, por ejemplo el entrecejo, la frente o las patas de gallo (ambos lados juntos). Otras zonas: Lip Flip, Brow Lift, comisuras de la boca, mentón en piel de naranja, Gummy Smile, arrugas del labio superior, Bunny Lines, afinado de la nariz.",
  q2: "¿Cuándo puedo volver al trabajo?",
  a2: "Justo después. Las pequeñas rojeces en los puntos de inyección suelen desaparecer en pocos minutos. Lo que debe tener en cuenta después lo hablamos de antemano.",
  q3: "¿Cuándo hace efecto el tratamiento de arrugas y cuánto dura?",
  a3: "El efecto suele empezar a los dos o tres días y es completo a las dos semanas aproximadamente. Por lo general dura de tres a seis meses, según cada persona.",
  q4: "¿Hay motivos para no tratar?",
  a4: "Sí, por ejemplo el embarazo y la lactancia, ciertas enfermedades musculares, infecciones agudas en la zona de tratamiento e intolerancias conocidas. Antes de cada tratamiento aclaramos en la conversación si es adecuado para usted.",
  ctaHA: "Su cita.",
  ctaHB: "Totalmente flexible.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Aviso legal",
  privacy: "Privacidad",
};

const fr: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Traitement médical des rides à Berlin",
  metaDesc: "PALO SKIN by Dr. Vogel à Berlin Prenzlauer Berg : traitement médical des rides du Dr med. Sebastian Vogel. Créneaux avant et après le travail et le week-end.",
  rateLong: "★ 5,0 avis clients",
  rateShort: "★ 5,0",
  rateAria: "Note de 5,0 dans les avis clients sur Google Maps",
  navAria: "Menu principal",
  navStudio: "Studio",
  navTreat: "Soins",
  navHow: "Déroulement",
  navFaq: "Questions",
  book: "Prendre rendez-vous",
  menu: "Menu",
  heroEyebrow: "Berlin Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Traitement médical des rides et Skin Booster. Au cœur du Kollwitzkiez.",
  googleA: "5,0",
  googleB: "sur Google",
  heroAlt: "Le Dr. med. Sebastian Vogel au studio PALO SKIN",
  docRole: "Médecin et fondateur de PALO SKIN",
  docEyebrow: "Votre médecin · formation chirurgicale",
  docHA: "Une main",
  docHB: "sûre.",
  handAlt: "Les mains du Dr Vogel posées calmement l’une sur l’autre sur la table noire du studio",
  quote: "« Je suis le Dr. med. Sebastian Vogel. J’ai travaillé plusieurs années en chirurgie et dans d’autres spécialités, et j’ai réalisé des milliers de soins esthétiques. Chez PALO SKIN, c’est moi qui vous soigne. Mon objectif : des résultats discrets, en accord avec votre visage. »",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Comment nous trouver",
  studioOpen: "Découvrir le studio",
  studioClose: "Fermer les photos",
  photoConsult: "Salle de consultation",
  photoTreat: "Salle de soin",
  photoStudio: "Au studio",
  photoEntrance: "Entrée",
  whyEyebrow: "Pour qui",
  whyHA: "Pour qui j’ai fondé",
  whyHB: "PALO SKIN.",
  why1H: "À l’heure, sans salle d’attente.",
  why1P: "Pour toutes celles et tous ceux qui glissent leur rendez-vous dans un quotidien bien rempli.",
  why2H: "Peu de paperasse.",
  why2P: "Pour les personnes qui aiment la simplicité : nous ne demandons que l’essentiel.",
  why3H: "Chaleureux plutôt qu’aseptisé.",
  why3P: "Pour celles et ceux qui veulent se sentir bien, même chez le médecin.",
  why4H: "Un soin dans votre langue.",
  why4P: "Pour Berlin et le monde entier : soins en allemand, anglais, espagnol, français et portugais.",
  why5H: "Des aiguilles très fines.",
  why5P: "Pour toutes celles et tous ceux qui souhaitent un soin aussi doux que possible.",
  why6H: "Uniquement des produits originaux.",
  why6P: "Pour les personnes qui veulent savoir ce qu’elles reçoivent : des produits issus de pharmacies allemandes.",
  treatEyebrow: "Soins et tarifs",
  treatHA: "Exactement ce qu’il vous faut.",
  treatHB: "Au juste prix.",
  t1H: "Traitement des rides et plus",
  t1D: "Ride du lion, front, pattes d’oie et autres zones.",
  t1Alt: "Pli de soie couleur crème",
  t2H: "Masséter (muscle de la mâchoire)",
  t2D: "Contour du visage et grincement des dents.",
  t2Alt: "Homme les yeux fermés, la main sur la joue",
  t3H: "Lifting Néfertiti",
  t3D: "Cou et contour de la mâchoire.",
  t3Alt: "Buste clair en pierre de Néfertiti, de profil",
  t4H: "ADN de saumon",
  t4D: "Polynucléotides pour les cernes et le contour des yeux.",
  t4Alt: "Contour des yeux d’une femme",
  priceFrom: (p) => `à partir de ${p}`,
  allPrices: "Voir tous les tarifs",
  pZones: "Traitement des rides et plus",
  pZone1: "1 zone",
  pZone2: "2 zones",
  pZone3: "3 zones",
  pZoneMore: "chaque zone supplémentaire",
  pNefD: "Cou et contour de la mâchoire",
  pAchselH: "Transpiration excessive (hyperhidrose)",
  pAchselD: "Aisselles",
  pLachsH: "ADN de saumon (polynucléotides)",
  pLachs1: "Une séance",
  pLachs4: "Quatre séances",
  pnote: "* Prix indicatifs. Facturation selon le barème allemand des honoraires médicaux (Gebührenordnung für Ärzte). Prix taxe sur la valeur ajoutée comprise.",
  howEyebrow: "Votre rendez-vous",
  howHA: "D’abord, l’échange.",
  howHB: "Ensuite, le soin.",
  s1H: "Quand cela vous convient.",
  s1P: "Des rendez-vous avant et après le travail, et aussi le week-end. Vous pouvez déplacer votre rendez-vous vous-même jusqu’à 24 heures avant.",
  s2H: "Une consultation approfondie.",
  s2P: "Que souhaitez-vous changer ? Nous parlons des possibilités, des limites, des risques et des coûts.",
  s3H: "Sans aucune pression.",
  s3P: "Si le soin vous convient, il peut avoir lieu directement lors du même rendez-vous. Et si vous préférez y réfléchir encore, nous vous accueillons tout aussi volontiers.",
  revEyebrow: "Avis",
  revHA: "Ce que disent",
  revHB: "nos clients.",
  allReviews: "Tous les avis sur Google Maps",
  faqHA: "Vos",
  faqHB: "questions.",
  q1: "Qu’est-ce qu’une zone ?",
  a1: "Une zone de traitement, par exemple la ride du lion, le front ou les pattes d’oie (les deux côtés ensemble). Autres zones : Lip Flip, Brow Lift, coins de la bouche, menton en peau d’orange, Gummy Smile, ridules de la lèvre supérieure, Bunny Lines, affinement du nez.",
  q2: "Quand puis-je retourner au travail ?",
  a2: "Juste après. Les petites rougeurs aux points d’injection disparaissent en général en quelques minutes. Nous voyons ensemble à l’avance à quoi faire attention ensuite.",
  q3: "Quand le traitement des rides agit-il et combien de temps dure-t-il ?",
  a3: "L’effet apparaît le plus souvent après deux à trois jours et est complet après environ deux semaines. Il dure en général de trois à six mois, cela varie d’une personne à l’autre.",
  q4: "Y a-t-il des cas où l’on ne traite pas ?",
  a4: "Oui, par exemple la grossesse et l’allaitement, certaines maladies musculaires, des infections aiguës dans la zone à traiter et des intolérances connues. Avant chaque soin, nous vérifions ensemble lors de l’entretien si ce traitement vous convient.",
  ctaHA: "Votre créneau.",
  ctaHB: "À la carte.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Mentions légales",
  privacy: "Confidentialité",
};

const pt: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Tratamento médico de rugas em Berlim",
  metaDesc: "PALO SKIN by Dr. Vogel em Berlim Prenzlauer Berg: tratamento médico de rugas pelo Dr. med. Sebastian Vogel. Horários antes e após o trabalho e no fim de semana.",
  rateLong: "★ 5,0 nas avaliações de clientes",
  rateShort: "★ 5,0",
  rateAria: "5,0 nas avaliações de clientes no Google Maps",
  navAria: "Menu principal",
  navStudio: "Estúdio",
  navTreat: "Tratamentos",
  navHow: "Como funciona",
  navFaq: "Perguntas",
  book: "Agendar",
  menu: "Menu",
  heroEyebrow: "Berlim Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Tratamento médico de rugas e Skin Booster. No coração do Kollwitzkiez.",
  googleA: "5,0",
  googleB: "no Google",
  heroAlt: "Dr. med. Sebastian Vogel no estúdio PALO SKIN",
  docRole: "Médico e fundador da PALO SKIN",
  docEyebrow: "Seu médico · formação cirúrgica",
  docHA: "Uma mão",
  docHB: "firme.",
  handAlt: "Mãos do Dr. Vogel pousadas calmamente uma sobre a outra na mesa preta do estúdio",
  quote: "“Sou o Dr. med. Sebastian Vogel. Trabalhei vários anos em cirurgia e em outras especialidades e realizei muitos milhares de tratamentos estéticos. Na PALO SKIN, eu mesmo cuido do seu tratamento. Meu objetivo são resultados discretos, que combinem com o seu rosto.”",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Como chegar",
  studioOpen: "Ver o estúdio",
  studioClose: "Fechar fotos",
  photoConsult: "Sala de consulta",
  photoTreat: "Sala de tratamento",
  photoStudio: "No estúdio",
  photoEntrance: "Entrada",
  whyEyebrow: "Para quem",
  whyHA: "Para quem eu fundei",
  whyHB: "a PALO SKIN.",
  why1H: "Pontual, sem sala de espera.",
  why1P: "Para quem precisa encaixar a consulta em um dia a dia cheio.",
  why2H: "Pouca papelada.",
  why2P: "Para quem gosta de simplicidade: perguntamos só o que importa.",
  why3H: "Aconchegante, não clínico.",
  why3P: "Para quem também quer se sentir à vontade no médico.",
  why4H: "Atendimento no seu idioma.",
  why4P: "Para Berlim e para o mundo: atendimento em alemão, inglês, espanhol, francês e português.",
  why5H: "Agulhas especialmente finas.",
  why5P: "Para quem deseja um tratamento o mais suave possível.",
  why6H: "Somente produtos originais.",
  why6P: "Para quem quer saber o que está recebendo: de farmácias alemãs.",
  treatEyebrow: "Tratamentos e preços",
  treatHA: "Exatamente o que você precisa.",
  treatHB: "A preços justos.",
  t1H: "Tratamento de rugas e mais",
  t1D: "Ruga entre as sobrancelhas, testa, pés de galinha e outras zonas.",
  t1Alt: "Dobra de seda em tom creme",
  t2H: "Masseter (músculo da mandíbula)",
  t2D: "Contorno do rosto e bruxismo.",
  t2Alt: "Homem de olhos fechados, com a mão na bochecha",
  t3H: "Lifting Nefertiti",
  t3D: "Pescoço e contorno da mandíbula.",
  t3Alt: "Busto claro de pedra de Nefertiti, de perfil",
  t4H: "DNA de salmão",
  t4D: "Polinucleotídeos para olheiras e a área dos olhos.",
  t4Alt: "Área dos olhos de uma mulher",
  priceFrom: (p) => `a partir de ${p}`,
  allPrices: "Ver todos os preços",
  pZones: "Tratamento de rugas e mais",
  pZone1: "1 zona",
  pZone2: "2 zonas",
  pZone3: "3 zonas",
  pZoneMore: "cada zona adicional",
  pNefD: "Pescoço e contorno da mandíbula",
  pAchselH: "Suor excessivo (hiperidrose)",
  pAchselD: "Axilas",
  pLachsH: "DNA de salmão (polinucleotídeos)",
  pLachs1: "Uma sessão",
  pLachs4: "Quatro sessões",
  pnote: "* Valores de referência. Cobrança conforme a tabela alemã de honorários médicos (Gebührenordnung für Ärzte). Preços com imposto sobre o valor agregado incluído.",
  howEyebrow: "Sua consulta",
  howHA: "Primeiro, a conversa.",
  howHB: "Depois, o tratamento.",
  s1H: "Quando for melhor para você.",
  s1P: "Horários antes e depois do trabalho e também aos fins de semana. Você pode remarcar por conta própria até 24 horas antes.",
  s2H: "Uma consulta detalhada.",
  s2P: "O que você gostaria de mudar? Falamos sobre possibilidades, limites, riscos e custos.",
  s3H: "Sem nenhuma pressão.",
  s3P: "Se o tratamento for adequado para você, ele pode ser feito na mesma consulta. E quem preferir pensar mais um pouco é igualmente bem-vindo.",
  revEyebrow: "Avaliações",
  revHA: "O que dizem",
  revHB: "sobre nós.",
  allReviews: "Todas as avaliações no Google Maps",
  faqHA: "Dúvidas",
  faqHB: "comuns.",
  q1: "O que é uma zona?",
  a1: "Uma área de tratamento, por exemplo a ruga entre as sobrancelhas, a testa ou os pés de galinha (os dois lados juntos). Outras zonas: Lip Flip, Brow Lift, cantos da boca, queixo em casca de laranja, Gummy Smile, rugas do lábio superior, Bunny Lines, afinamento do nariz.",
  q2: "Quando posso voltar ao trabalho?",
  a2: "Logo em seguida. Pequenas vermelhidões nos pontos de aplicação costumam desaparecer em poucos minutos. O que observar depois, conversamos com você antes.",
  q3: "Quando o tratamento de rugas faz efeito e quanto tempo dura?",
  a3: "O efeito costuma começar após dois a três dias e se completa em cerca de duas semanas. Em geral, dura de três a seis meses, o que varia de pessoa para pessoa.",
  q4: "Há motivos para não fazer o tratamento?",
  a4: "Sim, por exemplo gravidez e amamentação, certas doenças musculares, infecções agudas na área de tratamento e intolerâncias conhecidas. Antes de cada tratamento, esclarecemos na conversa se ele é adequado para você.",
  ctaHA: "Sua consulta.",
  ctaHB: "Bem flexível.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Informações legais",
  privacy: "Privacidade",
};

const it: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Trattamento medico delle rughe a Berlino",
  metaDesc: "PALO SKIN by Dr. Vogel a Berlino Prenzlauer Berg: trattamento medico delle rughe con il Dr. med. Sebastian Vogel. Orari prima e dopo il lavoro e nel weekend.",
  rateLong: "★ 5,0 nelle recensioni dei clienti",
  rateShort: "★ 5,0",
  rateAria: "5,0 nelle recensioni dei clienti su Google Maps",
  navAria: "Menu principale",
  navStudio: "Studio",
  navTreat: "Trattamenti",
  navHow: "Come funziona",
  navFaq: "Domande",
  book: "Prenota",
  menu: "Menu",
  heroEyebrow: "Berlino Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Trattamento medico delle rughe e Skin Booster. Nel cuore del Kollwitzkiez.",
  googleA: "5,0",
  googleB: "su Google",
  heroAlt: "Il Dr. med. Sebastian Vogel nello studio PALO SKIN",
  docRole: "Medico e fondatore di PALO SKIN",
  docEyebrow: "Il Suo medico · formazione chirurgica",
  docHA: "Una mano",
  docHB: "ferma.",
  handAlt: "Le mani del Dr. Vogel, posate con calma l’una sull’altra sul tavolo nero dello studio",
  quote: "«Sono il Dr. med. Sebastian Vogel. Ho lavorato per diversi anni in chirurgia e in altre specialità e ho eseguito molte migliaia di trattamenti estetici. Da PALO SKIN mi occupo io personalmente del Suo trattamento. Il mio obiettivo sono risultati discreti, in armonia con il Suo viso.»",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Come raggiungerci",
  studioOpen: "Scopra lo studio",
  studioClose: "Chiudi le foto",
  photoConsult: "Sala per la consulenza",
  photoTreat: "Sala trattamenti",
  photoStudio: "Nello studio",
  photoEntrance: "Ingresso",
  whyEyebrow: "Per chi",
  whyHA: "Per chi ho fondato",
  whyHB: "PALO SKIN.",
  why1H: "Puntualità invece della sala d’attesa.",
  why1P: "Per chi deve inserire l’appuntamento in una giornata piena.",
  why2H: "Pochissime scartoffie.",
  why2P: "Per chi ama le cose semplici: chiediamo solo ciò che conta.",
  why3H: "Accogliente, non clinico.",
  why3P: "Per chi vuole sentirsi a proprio agio anche dal medico.",
  why4H: "Trattamento in una lingua che Lei capisce.",
  why4P: "Per Berlino e il mondo: trattamento in tedesco, inglese, spagnolo, francese o portoghese.",
  why5H: "Aghi particolarmente sottili.",
  why5P: "Per chi desidera un trattamento il più delicato possibile.",
  why6H: "Solo preparati originali.",
  why6P: "Per chi vuole sapere che cosa riceve: da farmacie tedesche.",
  treatEyebrow: "Trattamenti e prezzi",
  treatHA: "Esattamente ciò di cui ha bisogno.",
  treatHB: "A prezzi equi.",
  t1H: "Trattamento delle rughe e altro",
  t1D: "Ruga del leone, fronte, zampe di gallina e altre zone.",
  t1Alt: "Piega di seta color crema",
  t2H: "Massetere (muscolo della masticazione)",
  t2D: "Contorno del viso e bruxismo.",
  t2Alt: "Uomo con gli occhi chiusi, la mano sulla guancia",
  t3H: "Nefertiti lift",
  t3D: "Collo e linea della mandibola.",
  t3Alt: "Busto in pietra chiara di Nefertiti, di profilo",
  t4H: "DNA di salmone",
  t4D: "Polinucleotidi per le occhiaie scure e il contorno occhi.",
  t4Alt: "Contorno occhi di una donna",
  priceFrom: (p) => `da ${p}`,
  allPrices: "Tutti i prezzi",
  pZones: "Trattamento delle rughe e altro",
  pZone1: "1 zona",
  pZone2: "2 zone",
  pZone3: "3 zone",
  pZoneMore: "ogni zona aggiuntiva",
  pNefD: "Collo e linea della mandibola",
  pAchselH: "Sudorazione eccessiva (iperidrosi)",
  pAchselD: "Ascelle",
  pLachsH: "DNA di salmone (polinucleotidi)",
  pLachs1: "Un trattamento",
  pLachs4: "Quattro trattamenti",
  pnote: "* Prezzi indicativi. Fatturazione secondo il tariffario tedesco degli onorari medici (Gebührenordnung für Ärzte). Prezzi comprensivi di imposta sul valore aggiunto.",
  howEyebrow: "Il Suo appuntamento",
  howHA: "Prima il colloquio.",
  howHB: "Poi il trattamento.",
  s1H: "Quando Le è più comodo.",
  s1P: "Appuntamenti prima e dopo il lavoro e anche nel fine settimana. Può spostare l’appuntamento in autonomia fino a 24 ore prima.",
  s2H: "Una consulenza approfondita.",
  s2P: "Che cosa vorrebbe cambiare? Parliamo di possibilità, limiti, rischi e costi.",
  s3H: "Senza alcuna pressione.",
  s3P: "Se il trattamento fa per Lei, è possibile farlo subito nello stesso appuntamento. E chi preferisce pensarci ancora è altrettanto benvenuto.",
  revEyebrow: "Recensioni",
  revHA: "Che cosa dicono",
  revHB: "i nostri clienti.",
  allReviews: "Tutte le recensioni su Google Maps",
  faqHA: "Domande",
  faqHB: "frequenti.",
  q1: "Che cos’è una zona?",
  a1: "Un’area di trattamento, per esempio la ruga del leone, la fronte o le zampe di gallina (entrambi i lati insieme). Altre zone: Lip Flip, Brow Lift, angoli della bocca, mento a buccia d’arancia, Gummy Smile, rughe del labbro superiore, Bunny Lines, assottigliamento del naso.",
  q2: "Quando posso tornare al lavoro?",
  a2: "Subito dopo. Piccoli arrossamenti nei punti di iniezione di solito scompaiono in pochi minuti. A che cosa prestare attenzione dopo il trattamento, ne parliamo prima.",
  q3: "Quando fa effetto il trattamento delle rughe e quanto dura?",
  a3: "L’effetto inizia di solito dopo due o tre giorni ed è completo dopo circa due settimane. In genere dura da tre a sei mesi, ma varia da persona a persona.",
  q4: "Ci sono motivi per non trattare?",
  a4: "Sì, per esempio gravidanza e allattamento, alcune malattie muscolari, infezioni acute nella zona da trattare e intolleranze note. Se il trattamento è adatto a Lei, lo chiariamo in un colloquio prima di ogni trattamento.",
  ctaHA: "Il Suo appuntamento.",
  ctaHB: "Con la massima flessibilità.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Note legali",
  privacy: "Privacy",
};

const tr: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Berlin’de tıbbi kırışıklık tedavisi",
  metaDesc: "PALO SKIN by Dr. Vogel, Berlin Prenzlauer Berg: Dr. med. Sebastian Vogel tarafından tıbbi kırışıklık tedavisi. İş öncesi, iş sonrası ve hafta sonu randevu.",
  rateLong: "★ 5,0 danışan değerlendirmesi",
  rateShort: "★ 5,0",
  rateAria: "Google Maps’te 5,0 danışan değerlendirmesi",
  navAria: "Ana menü",
  navStudio: "Stüdyo",
  navTreat: "Tedaviler",
  navHow: "Süreç",
  navFaq: "Sorular",
  book: "Randevu al",
  menu: "Menü",
  heroEyebrow: "Berlin Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Tıbbi kırışıklık tedavisi ve Skin Booster. Kollwitzkiez’in tam ortasında.",
  googleA: "5,0",
  googleB: "Google’da",
  heroAlt: "Dr. med. Sebastian Vogel, PALO SKIN stüdyosunda",
  docRole: "Hekim ve PALO SKIN’in kurucusu",
  docEyebrow: "Hekiminiz · cerrahi eğitimli",
  docHA: "Sakin bir",
  docHB: "el.",
  handAlt: "Dr. Vogel’in stüdyodaki siyah masanın üzerinde sakince üst üste duran elleri",
  quote: "“Ben Dr. med. Sebastian Vogel. Birkaç yıl cerrahide ve başka uzmanlık alanlarında çalıştım, binlerce estetik uygulama yaptım. PALO SKIN’de sizi bizzat ben tedavi ediyorum. Amacım, yüzünüze yakışan ölçülü sonuçlar.”",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Yol tarifi",
  studioOpen: "Stüdyoya göz atın",
  studioClose: "Fotoğrafları kapat",
  photoConsult: "Danışma odası",
  photoTreat: "Tedavi odası",
  photoStudio: "Stüdyoda",
  photoEntrance: "Giriş",
  whyEyebrow: "Kimler için",
  whyHA: "PALO SKIN’i kimler için",
  whyHB: "kurdum.",
  why1H: "Bekleme salonu yerine dakiklik.",
  why1P: "Randevusunu yoğun bir gündelik hayata sığdırmak zorunda olan herkes için.",
  why2H: "Neredeyse hiç evrak yok.",
  why2P: "Sadeliği sevenler için: Yalnızca önemli olanı soruyoruz.",
  why3H: "Steril değil, samimi.",
  why3P: "Doktordayken de kendini rahat hissetmek isteyenler için.",
  why4H: "Anladığınız bir dilde tedavi.",
  why4P: "Berlin ve dünya için: Almanca, İngilizce, İspanyolca, Fransızca ve Portekizce tedavi.",
  why5H: "Özellikle ince iğneler.",
  why5P: "Olabildiğince nazik bir tedavi isteyen herkes için.",
  why6H: "Yalnızca orijinal ürünler.",
  why6P: "Ne aldığını bilmek isteyenler için: Alman eczanelerinden.",
  treatEyebrow: "Tedaviler ve fiyatlar",
  treatHA: "Tam ihtiyacınız olan.",
  treatHB: "Adil fiyatlarla.",
  t1H: "Kırışıklık tedavisi ve dahası",
  t1D: "Kaş arası çizgileri, alın, kaz ayakları ve diğer bölgeler.",
  t1Alt: "Krem renginde ipek kıvrımı",
  t2H: "Çiğneme kası (masseter)",
  t2D: "Yüz hattı ve diş gıcırdatma.",
  t2Alt: "Gözleri kapalı, eli yanağında bir adam",
  t3H: "Nefertiti lifting",
  t3D: "Boyun ve çene hattı.",
  t3Alt: "Nefertiti’nin profilden açık renk taş büstü",
  t4H: "Somon DNA’sı",
  t4D: "Göz altı morlukları ve göz çevresi için polinükleotidler.",
  t4Alt: "Bir kadının göz çevresi",
  priceFrom: (p) => `${p} ve\u00A0üzeri`,
  allPrices: "Tüm fiyatları görün",
  pZones: "Kırışıklık tedavisi ve dahası",
  pZone1: "1 bölge",
  pZone2: "2 bölge",
  pZone3: "3 bölge",
  pZoneMore: "her ek bölge",
  pNefD: "Boyun ve çene hattı",
  pAchselH: "Aşırı terleme (hiperhidroz)",
  pAchselD: "Koltuk altı",
  pLachsH: "Somon DNA’sı (polinükleotidler)",
  pLachs1: "Tek seans",
  pLachs4: "Dört seans",
  pnote: "* Yaklaşık fiyatlar. Ücretlendirme, Alman hekim ücret tarifesine (Gebührenordnung für Ärzte) göre yapılır. Fiyatlara katma değer vergisi dahildir.",
  howEyebrow: "Randevunuz",
  howHA: "Önce görüşme.",
  howHB: "Sonra tedavi.",
  s1H: "Size ne zaman uygunsa.",
  s1P: "İş öncesi ve sonrası, hafta sonları da randevu. Randevunuzu 24 saat öncesine kadar kendiniz değiştirebilirsiniz.",
  s2H: "Ayrıntılı bir danışma.",
  s2P: "Neyi değiştirmek istersiniz? Olanakları, sınırları, riskleri ve maliyetleri konuşuruz.",
  s3H: "Hiçbir baskı olmadan.",
  s3P: "Tedavi size uygunsa aynı randevuda hemen yapılabilir. Biraz daha düşünmek isteyenleri de aynı şekilde memnuniyetle karşılıyoruz.",
  revEyebrow: "Değerlendirmeler",
  revHA: "Danışanlarımız",
  revHB: "hakkımızda ne diyor.",
  allReviews: "Google Maps’teki tüm değerlendirmeler",
  faqHA: "Sık sorulan",
  faqHB: "sorular.",
  q1: "Bölge nedir?",
  a1: "Bir tedavi alanı, örneğin kaş arası çizgileri, alın veya kaz ayakları (iki taraf birlikte). Diğer bölgeler: Lip Flip, Brow Lift, dudak kenarları, portakal kabuğu çene, Gummy Smile, üst dudak çizgileri, Bunny Lines, burun inceltme.",
  q2: "İşe ne zaman dönebilirim?",
  a2: "Hemen ardından. Enjeksiyon noktalarındaki küçük kızarıklıklar genellikle birkaç dakika içinde kaybolur. Sonrasında nelere dikkat etmeniz gerektiğini önceden konuşuruz.",
  q3: "Kırışıklık tedavisinin etkisi ne zaman başlar ve ne kadar sürer?",
  a3: "Etki çoğunlukla iki ila üç gün sonra başlar ve yaklaşık iki hafta sonra tam olarak ortaya çıkar. Genellikle üç ila altı ay sürer, bu kişiden kişiye değişir.",
  q4: "Tedavi yapılmaması için nedenler var mı?",
  a4: "Evet, örneğin hamilelik ve emzirme dönemi, belirli kas rahatsızlıkları, tedavi bölgesindeki akut enfeksiyonlar ve bilinen aşırı duyarlılıklar. Tedavinin size uygun olup olmadığını her tedaviden önce görüşmede netleştiriyoruz.",
  ctaHA: "Randevunuz.",
  ctaHB: "Tamamen esnek.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Yasal bildirim",
  privacy: "Gizlilik",
};

const uk: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | Лікарська корекція зморшок у Берліні",
  metaDesc: "PALO SKIN by Dr. Vogel у Берліні, Prenzlauer Berg: лікарська корекція зморшок від Dr. med. Sebastian Vogel. Прийом до та після роботи, а також у вихідні.",
  rateLong: "★ 5,0 відгуки клієнтів",
  rateShort: "★ 5,0",
  rateAria: "Оцінка 5,0 у відгуках клієнтів на Google Maps",
  navAria: "Головне меню",
  navStudio: "Студія",
  navTreat: "Процедури",
  navHow: "Як це відбувається",
  navFaq: "Питання",
  book: "Записатися",
  menu: "Меню",
  heroEyebrow: "Берлін, Prenzlauer Berg",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "Лікарська корекція зморшок і Skin Booster. У самому серці Kollwitzkiez.",
  googleA: "5,0",
  googleB: "на Google",
  heroAlt: "Dr. med. Sebastian Vogel у студії PALO SKIN",
  docRole: "Лікар і засновник PALO SKIN",
  docEyebrow: "Ваш лікар · хірургічна підготовка",
  docHA: "Спокійна",
  docHB: "рука.",
  handAlt: "Спокійно складені руки Dr. Vogel на чорному столі в студії",
  quote: "«Я Dr. med. Sebastian Vogel. Кілька років я працював у хірургії та інших галузях медицини і провів багато тисяч естетичних процедур. У PALO SKIN процедури Вам проводжу я сам. Моя мета: делікатні результати, які пасують саме Вашому обличчю.»",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "Як нас знайти",
  studioOpen: "Переглянути студію",
  studioClose: "Закрити фото",
  photoConsult: "Кімната для консультацій",
  photoTreat: "Кімната для процедур",
  photoStudio: "У студії",
  photoEntrance: "Вхід",
  whyEyebrow: "Для кого",
  whyHA: "Для кого я заснував",
  whyHB: "PALO SKIN.",
  why1H: "Вчасно, а не в черзі.",
  why1P: "Для всіх, кому треба вписати візит у насичені будні.",
  why2H: "Мінімум паперів.",
  why2P: "Для тих, хто любить простоту: ми питаємо лише про головне.",
  why3H: "Затишно, а не по-лікарняному.",
  why3P: "Для тих, хто хоче почуватися комфортно й у лікаря.",
  why4H: "Процедура зрозумілою Вам мовою.",
  why4P: "Для Берліна і всього світу: процедури німецькою, англійською, іспанською, французькою та португальською мовами.",
  why5H: "Особливо тонкі голки.",
  why5P: "Для всіх, хто бажає якомога делікатнішої процедури.",
  why6H: "Лише оригінальні препарати.",
  why6P: "Для тих, хто хоче знати, що отримує: препарати з німецьких аптек.",
  treatEyebrow: "Процедури та ціни",
  treatHA: "Саме те, що Вам потрібно.",
  treatHB: "За чесними цінами.",
  t1H: "Корекція зморшок і не тільки",
  t1D: "Міжбрівна зморшка, чоло, «гусячі лапки» та інші зони.",
  t1Alt: "Складка шовку кремового кольору",
  t2H: "Жувальний м’яз (масетер)",
  t2D: "Контур обличчя та скрегіт зубами.",
  t2Alt: "Чоловік із заплющеними очима, рука на щоці",
  t3H: "Ліфтинг Nefertiti",
  t3D: "Шия та контур нижньої щелепи.",
  t3Alt: "Світле кам’яне погруддя Нефертіті в профіль",
  t4H: "ДНК лосося",
  t4D: "Полінуклеотиди при темних колах під очима та для зони навколо очей.",
  t4Alt: "Ділянка навколо очей жінки",
  priceFrom: (p) => `від ${p}`,
  allPrices: "Переглянути всі ціни",
  pZones: "Корекція зморшок і не тільки",
  pZone1: "1 зона",
  pZone2: "2 зони",
  pZone3: "3 зони",
  pZoneMore: "кожна наступна зона",
  pNefD: "Шия та контур нижньої щелепи",
  pAchselH: "Надмірне потовиділення (гіпергідроз)",
  pAchselD: "Пахви",
  pLachsH: "ДНК лосося (полінуклеотиди)",
  pLachs1: "Одна процедура",
  pLachs4: "Чотири процедури",
  pnote: "* Орієнтовні ціни. Розрахунок згідно з німецьким тарифом на лікарські послуги (Gebührenordnung für Ärzte). Ціни включають податок на додану вартість.",
  howEyebrow: "Ваш візит",
  howHA: "Спершу розмова.",
  howHB: "Потім процедура.",
  s1H: "Коли Вам зручно.",
  s1P: "Час до і після роботи, а також у вихідні. Перенести запис Ви можете самостійно, не пізніше ніж за 24 години.",
  s2H: "Детальна консультація.",
  s2P: "Що Ви хотіли б змінити? Ми обговорюємо можливості, межі, ризики та вартість.",
  s3H: "Без жодного тиску.",
  s3P: "Якщо процедура Вам підходить, її можна провести одразу під час того самого візиту. А тим, хто хоче ще подумати, ми раді так само.",
  revEyebrow: "Відгуки",
  revHA: "Що клієнти",
  revHB: "кажуть про нас.",
  allReviews: "Усі відгуки на Google Maps",
  faqHA: "Часті",
  faqHB: "запитання.",
  q1: "Що таке зона?",
  a1: "Ділянка, яку обробляють під час процедури, наприклад міжбрівна зморшка, чоло або «гусячі лапки» (обидві сторони разом). Інші зони: Lip Flip, Brow Lift, куточки рота, підборіддя «апельсинова кірка», Gummy Smile, зморшки над верхньою губою, Bunny Lines, звуження носа.",
  q2: "Коли я зможу повернутися до роботи?",
  a2: "Одразу після процедури. Невелике почервоніння в місцях уколів зазвичай зникає за кілька хвилин. Що варто врахувати після процедури, ми обговоримо з Вами заздалегідь.",
  q3: "Коли з’являється ефект корекції зморшок і як довго він тримається?",
  a3: "Ефект зазвичай з’являється через два-три дні, а повністю проявляється приблизно через два тижні. Як правило, він тримається від трьох до шести місяців, у кожної людини по-різному.",
  q4: "Чи є причини не проводити процедуру?",
  a4: "Так, наприклад вагітність і грудне вигодовування, певні захворювання м’язів, гострі інфекції в зоні процедури та відома непереносимість. Чи підходить процедура саме Вам, ми з’ясовуємо в розмові перед кожною процедурою.",
  ctaHA: "Ваш візит.",
  ctaHB: "Як Вам зручно.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "Вихідні дані",
  privacy: "Захист даних",
};

const ar: HomeTexts = {
  title: "PALO SKIN by Dr. Vogel | علاج طبي للتجاعيد في برلين",
  metaDesc: "PALO SKIN by Dr. Vogel في Prenzlauer Berg ببرلين: علاج طبي للتجاعيد على يد Dr. med. Sebastian Vogel. مواعيد قبل العمل وبعده وفي عطلة نهاية الأسبوع.",
  rateLong: "★ 5.0 في تقييمات العملاء",
  rateShort: "★ 5.0",
  rateAria: "5.0 في تقييمات العملاء على Google Maps",
  navAria: "القائمة الرئيسية",
  navStudio: "المركز",
  navTreat: "العلاجات",
  navHow: "سير الزيارة",
  navFaq: "أسئلة",
  book: "حجز موعد",
  menu: "القائمة",
  heroEyebrow: "Prenzlauer Berg، برلين",
  h1A: "Goodbye",
  h1B: "wrinkles.",
  lead: "علاج طبي للتجاعيد وسكين بوستر. في قلب Kollwitzkiez.",
  googleA: "5.0",
  googleB: "على Google",
  heroAlt: "Dr. med. Sebastian Vogel في مركز PALO SKIN",
  docRole: "طبيب ومؤسس PALO SKIN",
  docEyebrow: "طبيبكم · بتدريب جراحي",
  docHA: "يد",
  docHB: "ثابتة.",
  handAlt: "يدا Dr. Vogel موضوعتان بهدوء إحداهما فوق الأخرى على الطاولة السوداء في المركز",
  quote: "«أنا Dr. med. Sebastian Vogel. عملتُ عدة سنوات في الجراحة وفي تخصصات طبية أخرى، وأجريتُ آلاف العلاجات التجميلية. في PALO SKIN أعالجكم بنفسي. هدفي نتائج طبيعية غير مبالغ فيها، تنسجم مع ملامح وجهكم.»",
  address: "Hagenauer Straße 14, 10435 Berlin, Prenzlauer Berg",
  mapL: "الطريق إلينا",
  studioOpen: "إلقاء نظرة على المركز",
  studioClose: "إغلاق الصور",
  photoConsult: "غرفة الاستشارة",
  photoTreat: "غرفة العلاج",
  photoStudio: "داخل المركز",
  photoEntrance: "المدخل",
  whyEyebrow: "لمن هذا المركز",
  whyHA: "لمن أسّستُ",
  whyHB: "PALO SKIN.",
  why1H: "في الموعد بدل غرفة الانتظار.",
  why1P: "لكل من يحتاج إلى إيجاد مكان لموعده في يوم مزدحم.",
  why2H: "أوراق قليلة جدًا.",
  why2P: "لمن يحب البساطة: لا نسأل إلا عمّا يهم.",
  why3H: "أجواء مريحة بدل الطابع السريري.",
  why3P: "لمن يرغب في الشعور بالراحة حتى عند الطبيب.",
  why4H: "العلاج بلغتكم.",
  why4P: "لبرلين وللعالم: العلاج بالألمانية والإنجليزية والإسبانية والفرنسية والبرتغالية.",
  why5H: "إبر رفيعة للغاية.",
  why5P: "لكل من يرغب في علاج لطيف قدر الإمكان.",
  why6H: "مستحضرات أصلية فقط.",
  why6P: "لمن يريد أن يعرف ما يحصل عليه: من صيدليات ألمانية.",
  treatEyebrow: "العلاجات والأسعار",
  treatHA: "ما تحتاجونه بالضبط.",
  treatHB: "بأسعار عادلة.",
  t1H: "علاج التجاعيد والمزيد",
  t1D: "خطوط ما بين الحاجبين، والجبهة، وتجاعيد زوايا العينين، ومناطق أخرى.",
  t1Alt: "طيّة حرير بلون كريمي",
  t2H: "عضلة المضغ (الماضغة)",
  t2D: "محيط الوجه وصرير الأسنان.",
  t2Alt: "رجل مغمض العينين، يده على خده",
  t3H: "شد نفرتيتي",
  t3D: "الرقبة وخط الفك.",
  t3Alt: "تمثال نصفي حجري فاتح لنفرتيتي من الجانب",
  t4H: "الحمض النووي للسلمون",
  t4D: "بولي نيوكليوتيدات للهالات السوداء ومنطقة حول العينين.",
  t4Alt: "منطقة العينين لدى امرأة",
  priceFrom: (p) => `ابتداءً من ${p}`,
  allPrices: "الاطلاع على جميع الأسعار",
  pZones: "علاج التجاعيد والمزيد",
  pZone1: "منطقة واحدة",
  pZone2: "منطقتان",
  pZone3: "3 مناطق",
  pZoneMore: "كل منطقة إضافية",
  pNefD: "الرقبة وخط الفك",
  pAchselH: "التعرق المفرط (فرط التعرق)",
  pAchselD: "منطقة الإبطين",
  pLachsH: "الحمض النووي للسلمون (بولي نيوكليوتيدات)",
  pLachs1: "جلسة واحدة",
  pLachs4: "أربع جلسات",
  pnote: "* أسعار استرشادية. تتم المحاسبة وفق لائحة أتعاب الأطباء الألمانية (Gebührenordnung für Ärzte). الأسعار شاملة ضريبة القيمة المضافة.",
  howEyebrow: "موعدكم",
  howHA: "أولًا نتحدث معًا.",
  howHB: "ثم العلاج.",
  s1H: "في الوقت الذي يناسبكم.",
  s1P: "مواعيد قبل العمل وبعده، وفي عطلة نهاية الأسبوع أيضًا. ويمكنكم تغيير الموعد بأنفسكم حتى 24 ساعة قبله.",
  s2H: "استشارة مفصّلة.",
  s2P: "ما الذي ترغبون في تغييره؟ نناقش معًا الإمكانيات والحدود والمخاطر والتكاليف.",
  s3H: "دون أي ضغط.",
  s3P: "إذا كان العلاج مناسبًا لكم، يمكن إجراؤه مباشرة في الموعد نفسه. ومن يفضّل التفكير مرة أخرى، فهو مرحَّب به بالقدر نفسه.",
  revEyebrow: "التقييمات",
  revHA: "ما يقوله عملاؤنا",
  revHB: "عنّا.",
  allReviews: "جميع التقييمات على Google Maps",
  faqHA: "أسئلة",
  faqHB: "شائعة.",
  q1: "ما المقصود بالمنطقة؟",
  a1: "منطقة علاج واحدة، مثل خطوط ما بين الحاجبين أو الجبهة أو تجاعيد زوايا العينين (الجانبان معًا). ومن المناطق الأخرى: ليب فليب، ورفع الحاجبين، وزوايا الفم، وتجعّد الذقن، والابتسامة اللثوية، وتجاعيد الشفة العليا، وتجاعيد جانبي الأنف، وتنحيف الأنف.",
  q2: "متى يمكنني العودة إلى العمل؟",
  a2: "مباشرة بعد العلاج. يختفي الاحمرار الخفيف في مواضع الحقن عادةً خلال دقائق قليلة. ونناقش معكم مسبقًا ما ينبغي مراعاته بعد العلاج.",
  q3: "متى يبدأ مفعول علاج التجاعيد، وكم يدوم؟",
  a3: "يبدأ المفعول عادةً بعد يومين إلى ثلاثة أيام، ويكتمل بعد نحو أسبوعين. ويستمر في الغالب من ثلاثة إلى ستة أشهر، ويختلف ذلك من شخص لآخر.",
  q4: "هل توجد أسباب تمنع العلاج؟",
  a4: "نعم، مثل الحمل والرضاعة، وبعض أمراض العضلات، والالتهابات الحادة في منطقة العلاج، وحالات عدم التحمل المعروفة. ونوضح معكم في الحديث قبل كل علاج ما إذا كان العلاج مناسبًا لكم.",
  ctaHA: "موعدكم.",
  ctaHB: "بكل مرونة.",
  copyright: "© 2026 PALO SKIN by Dr. Vogel",
  imprint: "الإشعار القانوني",
  privacy: "حماية البيانات",
};

export const HOME_TEXTS: Record<Lang, HomeTexts> = { de, en, es, fr, pt, it, tr, uk, ar };


/* Französisch: schmales geschütztes Leerzeichen vor ? ! : ; und innerhalb der Anführungszeichen (wie in lib/texts.ts) */
{
  const fr = HOME_TEXTS.fr as unknown as Record<string, unknown>;
  for (const k of Object.keys(fr)) {
    const v = fr[k];
    if (typeof v === "string") fr[k] = v.replace(/ ([?!:;»])/g, " $1").replace(/« /g, "« ");
  }
}
